// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface BelongLandInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.BelongLandInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 归属的玩家ID
   * </pre>
   *
   * <code>optional int64 playerId = 1;</code>
   */
  boolean hasPlayerId();
  /**
   * <pre>
   * 归属的玩家ID
   * </pre>
   *
   * <code>optional int64 playerId = 1;</code>
   */
  long getPlayerId();

  /**
   * <pre>
   * 城池归属 玩家名
   * </pre>
   *
   * <code>optional string playerName = 2;</code>
   */
  boolean hasPlayerName();
  /**
   * <pre>
   * 城池归属 玩家名
   * </pre>
   *
   * <code>optional string playerName = 2;</code>
   */
  java.lang.String getPlayerName();
  /**
   * <pre>
   * 城池归属 玩家名
   * </pre>
   *
   * <code>optional string playerName = 2;</code>
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();

  /**
   * <pre>
   *玩家头像id
   * </pre>
   *
   * <code>optional int32 photoId = 3;</code>
   */
  boolean hasPhotoId();
  /**
   * <pre>
   *玩家头像id
   * </pre>
   *
   * <code>optional int32 photoId = 3;</code>
   */
  int getPhotoId();

  /**
   * <pre>
   * 联盟简称
   * </pre>
   *
   * <code>optional string allianceShortName = 4;</code>
   */
  boolean hasAllianceShortName();
  /**
   * <pre>
   * 联盟简称
   * </pre>
   *
   * <code>optional string allianceShortName = 4;</code>
   */
  java.lang.String getAllianceShortName();
  /**
   * <pre>
   * 联盟简称
   * </pre>
   *
   * <code>optional string allianceShortName = 4;</code>
   */
  com.google.protobuf.ByteString
      getAllianceShortNameBytes();

  /**
   * <pre>
   *归属结束时间
   * </pre>
   *
   * <code>optional int32 belongOverTime = 5;</code>
   */
  boolean hasBelongOverTime();
  /**
   * <pre>
   *归属结束时间
   * </pre>
   *
   * <code>optional int32 belongOverTime = 5;</code>
   */
  int getBelongOverTime();

  /**
   * <pre>
   *属地简单战果
   * </pre>
   *
   * <code>optional .client2server.BattleSimpleRs battleSimpleRs = 6;</code>
   */
  boolean hasBattleSimpleRs();
  /**
   * <pre>
   *属地简单战果
   * </pre>
   *
   * <code>optional .client2server.BattleSimpleRs battleSimpleRs = 6;</code>
   */
  pb4client.BattleSimpleRs getBattleSimpleRs();
  /**
   * <pre>
   *属地简单战果
   * </pre>
   *
   * <code>optional .client2server.BattleSimpleRs battleSimpleRs = 6;</code>
   */
  pb4client.BattleSimpleRsOrBuilder getBattleSimpleRsOrBuilder();

  /**
   * <pre>
   * (客户端使用)
   * </pre>
   *
   * <code>optional int32 tileId = 100;</code>
   */
  boolean hasTileId();
  /**
   * <pre>
   * (客户端使用)
   * </pre>
   *
   * <code>optional int32 tileId = 100;</code>
   */
  int getTileId();
}
