// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface ChangeGroupRtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.ChangeGroupRt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 rt = 1;</code>
   */
  boolean hasRt();
  /**
   * <code>required int32 rt = 1;</code>
   */
  int getRt();

  /**
   * <pre>
   * </pre>
   *
   * <code>optional int64 groupId = 2;</code>
   */
  boolean hasGroupId();
  /**
   * <pre>
   * </pre>
   *
   * <code>optional int64 groupId = 2;</code>
   */
  long getGroupId();

  /**
   * <code>optional string newName = 3;</code>
   */
  boolean hasNewName();
  /**
   * <code>optional string newName = 3;</code>
   */
  java.lang.String getNewName();
  /**
   * <code>optional string newName = 3;</code>
   */
  com.google.protobuf.ByteString
      getNewNameBytes();
}
