// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface ClearTimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.ClearTime)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 要加速的功能  1-科技 2-造兵 3-秒治疗兵 4-秒建筑 5- 秒锻造  6- 秒武将升星  7-秒武将升阶  8 -秒晋升  9-秒联盟宝藏  12-秒治疗兵(活动)
   * </pre>
   *
   * <code>required int32 clearType = 1;</code>
   */
  boolean hasClearType();
  /**
   * <pre>
   * 要加速的功能  1-科技 2-造兵 3-秒治疗兵 4-秒建筑 5- 秒锻造  6- 秒武将升星  7-秒武将升阶  8 -秒晋升  9-秒联盟宝藏  12-秒治疗兵(活动)
   * </pre>
   *
   * <code>required int32 clearType = 1;</code>
   */
  int getClearType();

  /**
   * <pre>
   * 加速的道具ID 如果这个跟下面的字段都传0的话,就认为是元宝秒所有CD
   * </pre>
   *
   * <code>required int32 clearPropsId = 2;</code>
   */
  boolean hasClearPropsId();
  /**
   * <pre>
   * 加速的道具ID 如果这个跟下面的字段都传0的话,就认为是元宝秒所有CD
   * </pre>
   *
   * <code>required int32 clearPropsId = 2;</code>
   */
  int getClearPropsId();

  /**
   * <pre>
   * 使用的加速道具的数量
   * </pre>
   *
   * <code>required int32 clearPropsNum = 3;</code>
   */
  boolean hasClearPropsNum();
  /**
   * <pre>
   * 使用的加速道具的数量
   * </pre>
   *
   * <code>required int32 clearPropsNum = 3;</code>
   */
  int getClearPropsNum();

  /**
   * <pre>
   *扩展字段
   * </pre>
   *
   * <code>required int64 extend1 = 4;</code>
   */
  boolean hasExtend1();
  /**
   * <pre>
   *扩展字段
   * </pre>
   *
   * <code>required int64 extend1 = 4;</code>
   */
  long getExtend1();
}
