// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface CtrlNoticeOfflineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.CtrlNoticeOffline)
    com.google.protobuf.MessageOrBuilder {
}
