// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface DelKingEquipPlanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.DelKingEquipPlan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 排序ID
   * </pre>
   *
   * <code>required int32 planId = 1;</code>
   */
  boolean hasPlanId();
  /**
   * <pre>
   * 排序ID
   * </pre>
   *
   * <code>required int32 planId = 1;</code>
   */
  int getPlanId();
}
