// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface EditorCountryNoticeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.EditorCountryNotice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *公告内容
   * </pre>
   *
   * <code>required string notice = 1;</code>
   */
  boolean hasNotice();
  /**
   * <pre>
   *公告内容
   * </pre>
   *
   * <code>required string notice = 1;</code>
   */
  java.lang.String getNotice();
  /**
   * <pre>
   *公告内容
   * </pre>
   *
   * <code>required string notice = 1;</code>
   */
  com.google.protobuf.ByteString
      getNoticeBytes();
}
