// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

/**
 * Protobuf type {@code client2server.FameHallInfo}
 */
public  final class FameHallInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:client2server.FameHallInfo)
    FameHallInfoOrBuilder {
  // Use FameHallInfo.newBuilder() to construct.
  private FameHallInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FameHallInfo() {
    occupyTime_ = 0;
    createTime_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FameHallInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            pb4client.PlayerNameInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = playerNameInfo_.toBuilder();
            }
            playerNameInfo_ = input.readMessage(pb4client.PlayerNameInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(playerNameInfo_);
              playerNameInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            occupyTime_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            createTime_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pb4client.War2GamePkt.internal_static_client2server_FameHallInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pb4client.War2GamePkt.internal_static_client2server_FameHallInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pb4client.FameHallInfo.class, pb4client.FameHallInfo.Builder.class);
  }

  private int bitField0_;
  public static final int PLAYERNAMEINFO_FIELD_NUMBER = 1;
  private pb4client.PlayerNameInfo playerNameInfo_;
  /**
   * <code>required .client2server.PlayerNameInfo playerNameInfo = 1;</code>
   */
  public boolean hasPlayerNameInfo() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .client2server.PlayerNameInfo playerNameInfo = 1;</code>
   */
  public pb4client.PlayerNameInfo getPlayerNameInfo() {
    return playerNameInfo_ == null ? pb4client.PlayerNameInfo.getDefaultInstance() : playerNameInfo_;
  }
  /**
   * <code>required .client2server.PlayerNameInfo playerNameInfo = 1;</code>
   */
  public pb4client.PlayerNameInfoOrBuilder getPlayerNameInfoOrBuilder() {
    return playerNameInfo_ == null ? pb4client.PlayerNameInfo.getDefaultInstance() : playerNameInfo_;
  }

  public static final int OCCUPYTIME_FIELD_NUMBER = 2;
  private int occupyTime_;
  /**
   * <pre>
   * 占领奇观时长
   * </pre>
   *
   * <code>required int32 occupyTime = 2;</code>
   */
  public boolean hasOccupyTime() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * 占领奇观时长
   * </pre>
   *
   * <code>required int32 occupyTime = 2;</code>
   */
  public int getOccupyTime() {
    return occupyTime_;
  }

  public static final int CREATETIME_FIELD_NUMBER = 3;
  private int createTime_;
  /**
   * <pre>
   * 占领时间
   * </pre>
   *
   * <code>required int32 createTime = 3;</code>
   */
  public boolean hasCreateTime() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   * 占领时间
   * </pre>
   *
   * <code>required int32 createTime = 3;</code>
   */
  public int getCreateTime() {
    return createTime_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasPlayerNameInfo()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasOccupyTime()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasCreateTime()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getPlayerNameInfo().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getPlayerNameInfo());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, occupyTime_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, createTime_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPlayerNameInfo());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, occupyTime_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, createTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pb4client.FameHallInfo)) {
      return super.equals(obj);
    }
    pb4client.FameHallInfo other = (pb4client.FameHallInfo) obj;

    boolean result = true;
    result = result && (hasPlayerNameInfo() == other.hasPlayerNameInfo());
    if (hasPlayerNameInfo()) {
      result = result && getPlayerNameInfo()
          .equals(other.getPlayerNameInfo());
    }
    result = result && (hasOccupyTime() == other.hasOccupyTime());
    if (hasOccupyTime()) {
      result = result && (getOccupyTime()
          == other.getOccupyTime());
    }
    result = result && (hasCreateTime() == other.hasCreateTime());
    if (hasCreateTime()) {
      result = result && (getCreateTime()
          == other.getCreateTime());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPlayerNameInfo()) {
      hash = (37 * hash) + PLAYERNAMEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerNameInfo().hashCode();
    }
    if (hasOccupyTime()) {
      hash = (37 * hash) + OCCUPYTIME_FIELD_NUMBER;
      hash = (53 * hash) + getOccupyTime();
    }
    if (hasCreateTime()) {
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pb4client.FameHallInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4client.FameHallInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4client.FameHallInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4client.FameHallInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4client.FameHallInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4client.FameHallInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4client.FameHallInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb4client.FameHallInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb4client.FameHallInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pb4client.FameHallInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb4client.FameHallInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb4client.FameHallInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pb4client.FameHallInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code client2server.FameHallInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:client2server.FameHallInfo)
      pb4client.FameHallInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb4client.War2GamePkt.internal_static_client2server_FameHallInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb4client.War2GamePkt.internal_static_client2server_FameHallInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb4client.FameHallInfo.class, pb4client.FameHallInfo.Builder.class);
    }

    // Construct using pb4client.FameHallInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPlayerNameInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (playerNameInfoBuilder_ == null) {
        playerNameInfo_ = null;
      } else {
        playerNameInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      occupyTime_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      createTime_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pb4client.War2GamePkt.internal_static_client2server_FameHallInfo_descriptor;
    }

    public pb4client.FameHallInfo getDefaultInstanceForType() {
      return pb4client.FameHallInfo.getDefaultInstance();
    }

    public pb4client.FameHallInfo build() {
      pb4client.FameHallInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public pb4client.FameHallInfo buildPartial() {
      pb4client.FameHallInfo result = new pb4client.FameHallInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (playerNameInfoBuilder_ == null) {
        result.playerNameInfo_ = playerNameInfo_;
      } else {
        result.playerNameInfo_ = playerNameInfoBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.occupyTime_ = occupyTime_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.createTime_ = createTime_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pb4client.FameHallInfo) {
        return mergeFrom((pb4client.FameHallInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pb4client.FameHallInfo other) {
      if (other == pb4client.FameHallInfo.getDefaultInstance()) return this;
      if (other.hasPlayerNameInfo()) {
        mergePlayerNameInfo(other.getPlayerNameInfo());
      }
      if (other.hasOccupyTime()) {
        setOccupyTime(other.getOccupyTime());
      }
      if (other.hasCreateTime()) {
        setCreateTime(other.getCreateTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasPlayerNameInfo()) {
        return false;
      }
      if (!hasOccupyTime()) {
        return false;
      }
      if (!hasCreateTime()) {
        return false;
      }
      if (!getPlayerNameInfo().isInitialized()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pb4client.FameHallInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pb4client.FameHallInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private pb4client.PlayerNameInfo playerNameInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        pb4client.PlayerNameInfo, pb4client.PlayerNameInfo.Builder, pb4client.PlayerNameInfoOrBuilder> playerNameInfoBuilder_;
    /**
     * <code>required .client2server.PlayerNameInfo playerNameInfo = 1;</code>
     */
    public boolean hasPlayerNameInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .client2server.PlayerNameInfo playerNameInfo = 1;</code>
     */
    public pb4client.PlayerNameInfo getPlayerNameInfo() {
      if (playerNameInfoBuilder_ == null) {
        return playerNameInfo_ == null ? pb4client.PlayerNameInfo.getDefaultInstance() : playerNameInfo_;
      } else {
        return playerNameInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>required .client2server.PlayerNameInfo playerNameInfo = 1;</code>
     */
    public Builder setPlayerNameInfo(pb4client.PlayerNameInfo value) {
      if (playerNameInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playerNameInfo_ = value;
        onChanged();
      } else {
        playerNameInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .client2server.PlayerNameInfo playerNameInfo = 1;</code>
     */
    public Builder setPlayerNameInfo(
        pb4client.PlayerNameInfo.Builder builderForValue) {
      if (playerNameInfoBuilder_ == null) {
        playerNameInfo_ = builderForValue.build();
        onChanged();
      } else {
        playerNameInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .client2server.PlayerNameInfo playerNameInfo = 1;</code>
     */
    public Builder mergePlayerNameInfo(pb4client.PlayerNameInfo value) {
      if (playerNameInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            playerNameInfo_ != null &&
            playerNameInfo_ != pb4client.PlayerNameInfo.getDefaultInstance()) {
          playerNameInfo_ =
            pb4client.PlayerNameInfo.newBuilder(playerNameInfo_).mergeFrom(value).buildPartial();
        } else {
          playerNameInfo_ = value;
        }
        onChanged();
      } else {
        playerNameInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .client2server.PlayerNameInfo playerNameInfo = 1;</code>
     */
    public Builder clearPlayerNameInfo() {
      if (playerNameInfoBuilder_ == null) {
        playerNameInfo_ = null;
        onChanged();
      } else {
        playerNameInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .client2server.PlayerNameInfo playerNameInfo = 1;</code>
     */
    public pb4client.PlayerNameInfo.Builder getPlayerNameInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getPlayerNameInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>required .client2server.PlayerNameInfo playerNameInfo = 1;</code>
     */
    public pb4client.PlayerNameInfoOrBuilder getPlayerNameInfoOrBuilder() {
      if (playerNameInfoBuilder_ != null) {
        return playerNameInfoBuilder_.getMessageOrBuilder();
      } else {
        return playerNameInfo_ == null ?
            pb4client.PlayerNameInfo.getDefaultInstance() : playerNameInfo_;
      }
    }
    /**
     * <code>required .client2server.PlayerNameInfo playerNameInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pb4client.PlayerNameInfo, pb4client.PlayerNameInfo.Builder, pb4client.PlayerNameInfoOrBuilder> 
        getPlayerNameInfoFieldBuilder() {
      if (playerNameInfoBuilder_ == null) {
        playerNameInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pb4client.PlayerNameInfo, pb4client.PlayerNameInfo.Builder, pb4client.PlayerNameInfoOrBuilder>(
                getPlayerNameInfo(),
                getParentForChildren(),
                isClean());
        playerNameInfo_ = null;
      }
      return playerNameInfoBuilder_;
    }

    private int occupyTime_ ;
    /**
     * <pre>
     * 占领奇观时长
     * </pre>
     *
     * <code>required int32 occupyTime = 2;</code>
     */
    public boolean hasOccupyTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 占领奇观时长
     * </pre>
     *
     * <code>required int32 occupyTime = 2;</code>
     */
    public int getOccupyTime() {
      return occupyTime_;
    }
    /**
     * <pre>
     * 占领奇观时长
     * </pre>
     *
     * <code>required int32 occupyTime = 2;</code>
     */
    public Builder setOccupyTime(int value) {
      bitField0_ |= 0x00000002;
      occupyTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 占领奇观时长
     * </pre>
     *
     * <code>required int32 occupyTime = 2;</code>
     */
    public Builder clearOccupyTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      occupyTime_ = 0;
      onChanged();
      return this;
    }

    private int createTime_ ;
    /**
     * <pre>
     * 占领时间
     * </pre>
     *
     * <code>required int32 createTime = 3;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 占领时间
     * </pre>
     *
     * <code>required int32 createTime = 3;</code>
     */
    public int getCreateTime() {
      return createTime_;
    }
    /**
     * <pre>
     * 占领时间
     * </pre>
     *
     * <code>required int32 createTime = 3;</code>
     */
    public Builder setCreateTime(int value) {
      bitField0_ |= 0x00000004;
      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 占领时间
     * </pre>
     *
     * <code>required int32 createTime = 3;</code>
     */
    public Builder clearCreateTime() {
      bitField0_ = (bitField0_ & ~0x00000004);
      createTime_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:client2server.FameHallInfo)
  }

  // @@protoc_insertion_point(class_scope:client2server.FameHallInfo)
  private static final pb4client.FameHallInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pb4client.FameHallInfo();
  }

  public static pb4client.FameHallInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<FameHallInfo>
      PARSER = new com.google.protobuf.AbstractParser<FameHallInfo>() {
    public FameHallInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FameHallInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FameHallInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FameHallInfo> getParserForType() {
    return PARSER;
  }

  public pb4client.FameHallInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

