// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface FightRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.FightRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *帧
   * </pre>
   *
   * <code>required int32 frame = 1;</code>
   */
  boolean hasFrame();
  /**
   * <pre>
   *帧
   * </pre>
   *
   * <code>required int32 frame = 1;</code>
   */
  int getFrame();

  /**
   * <pre>
   *发送者Id
   * </pre>
   *
   * <code>required int64 senderId = 2;</code>
   */
  boolean hasSenderId();
  /**
   * <pre>
   *发送者Id
   * </pre>
   *
   * <code>required int64 senderId = 2;</code>
   */
  long getSenderId();

  /**
   * <pre>
   *接受者Id
   * </pre>
   *
   * <code>required int64 receiverId = 3;</code>
   */
  boolean hasReceiverId();
  /**
   * <pre>
   *接受者Id
   * </pre>
   *
   * <code>required int64 receiverId = 3;</code>
   */
  long getReceiverId();

  /**
   * <pre>
   *请求内容
   * </pre>
   *
   * <code>required .client2server.FightRequest request = 4;</code>
   */
  boolean hasRequest();
  /**
   * <pre>
   *请求内容
   * </pre>
   *
   * <code>required .client2server.FightRequest request = 4;</code>
   */
  pb4client.FightRequest getRequest();
  /**
   * <pre>
   *请求内容
   * </pre>
   *
   * <code>required .client2server.FightRequest request = 4;</code>
   */
  pb4client.FightRequestOrBuilder getRequestOrBuilder();
}
