// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface FightStatisticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.FightStatistics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 recordKey = 1;</code>
   */
  boolean hasRecordKey();
  /**
   * <code>required int32 recordKey = 1;</code>
   */
  int getRecordKey();

  /**
   * <code>required int32 recordValue = 2;</code>
   */
  boolean hasRecordValue();
  /**
   * <code>required int32 recordValue = 2;</code>
   */
  int getRecordValue();
}
