// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface FurnitureTimeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.FurnitureTimeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 家具唯一Id
   * </pre>
   *
   * <code>required int64 id = 1;</code>
   */
  boolean hasId();
  /**
   * <pre>
   * 家具唯一Id
   * </pre>
   *
   * <code>required int64 id = 1;</code>
   */
  long getId();

  /**
   * <pre>
   * 收集开始时间
   * </pre>
   *
   * <code>required int32 startTime = 2;</code>
   */
  boolean hasStartTime();
  /**
   * <pre>
   * 收集开始时间
   * </pre>
   *
   * <code>required int32 startTime = 2;</code>
   */
  int getStartTime();

  /**
   * <pre>
   * 收集满时间
   * </pre>
   *
   * <code>required int32 endTime = 3;</code>
   */
  boolean hasEndTime();
  /**
   * <pre>
   * 收集满时间
   * </pre>
   *
   * <code>required int32 endTime = 3;</code>
   */
  int getEndTime();
}
