// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface LotteryChangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.LotteryChange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 变化内容
   * </pre>
   *
   * <code>required .client2server.LotteryInfo lotteryInfo = 1;</code>
   */
  boolean hasLotteryInfo();
  /**
   * <pre>
   * 变化内容
   * </pre>
   *
   * <code>required .client2server.LotteryInfo lotteryInfo = 1;</code>
   */
  pb4client.LotteryInfo getLotteryInfo();
  /**
   * <pre>
   * 变化内容
   * </pre>
   *
   * <code>required .client2server.LotteryInfo lotteryInfo = 1;</code>
   */
  pb4client.LotteryInfoOrBuilder getLotteryInfoOrBuilder();
}
