// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface MakeFriendOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.MakeFriend)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 好友ID
   * </pre>
   *
   * <code>required int64 tarPlayerId = 1;</code>
   */
  boolean hasTarPlayerId();
  /**
   * <pre>
   * 好友ID
   * </pre>
   *
   * <code>required int64 tarPlayerId = 1;</code>
   */
  long getTarPlayerId();
}
