// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface OnEquipRtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.OnEquipRt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 返回值
   * </pre>
   *
   * <code>required int32 rt = 1;</code>
   */
  boolean hasRt();
  /**
   * <pre>
   * 返回值
   * </pre>
   *
   * <code>required int32 rt = 1;</code>
   */
  int getRt();

  /**
   * <pre>
   * 要穿的装备ID
   * </pre>
   *
   * <code>optional int64 equipId = 2;</code>
   */
  boolean hasEquipId();
  /**
   * <pre>
   * 要穿的装备ID
   * </pre>
   *
   * <code>optional int64 equipId = 2;</code>
   */
  long getEquipId();

  /**
   * <pre>
   * 穿戴的武将ID
   * </pre>
   *
   * <code>optional int64 heroId = 3;</code>
   */
  boolean hasHeroId();
  /**
   * <pre>
   * 穿戴的武将ID
   * </pre>
   *
   * <code>optional int64 heroId = 3;</code>
   */
  long getHeroId();
}
