// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface OpenOnlineRewardRtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.OpenOnlineRewardRt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 返回值
   * </pre>
   *
   * <code>required int32 rt = 1;</code>
   */
  boolean hasRt();
  /**
   * <pre>
   * 返回值
   * </pre>
   *
   * <code>required int32 rt = 1;</code>
   */
  int getRt();

  /**
   * <pre>
   * 玩家在线礼包信息
   * </pre>
   *
   * <code>optional .client2server.OnlineRewardInfo onlineRewardInfo = 2;</code>
   */
  boolean hasOnlineRewardInfo();
  /**
   * <pre>
   * 玩家在线礼包信息
   * </pre>
   *
   * <code>optional .client2server.OnlineRewardInfo onlineRewardInfo = 2;</code>
   */
  pb4client.OnlineRewardInfo getOnlineRewardInfo();
  /**
   * <pre>
   * 玩家在线礼包信息
   * </pre>
   *
   * <code>optional .client2server.OnlineRewardInfo onlineRewardInfo = 2;</code>
   */
  pb4client.OnlineRewardInfoOrBuilder getOnlineRewardInfoOrBuilder();
}
