// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface PlayerRewardBagInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.PlayerRewardBagInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 奖励信息
   * </pre>
   *
   * <code>required string reward = 1;</code>
   */
  boolean hasReward();
  /**
   * <pre>
   * 奖励信息
   * </pre>
   *
   * <code>required string reward = 1;</code>
   */
  java.lang.String getReward();
  /**
   * <pre>
   * 奖励信息
   * </pre>
   *
   * <code>required string reward = 1;</code>
   */
  com.google.protobuf.ByteString
      getRewardBytes();

  /**
   * <pre>
   * 来源lanId
   * </pre>
   *
   * <code>required string landId = 2;</code>
   */
  boolean hasLandId();
  /**
   * <pre>
   * 来源lanId
   * </pre>
   *
   * <code>required string landId = 2;</code>
   */
  java.lang.String getLandId();
  /**
   * <pre>
   * 来源lanId
   * </pre>
   *
   * <code>required string landId = 2;</code>
   */
  com.google.protobuf.ByteString
      getLandIdBytes();

  /**
   * <pre>
   *lan参数
   * </pre>
   *
   * <code>repeated string lanParas = 3;</code>
   */
  java.util.List<java.lang.String>
      getLanParasList();
  /**
   * <pre>
   *lan参数
   * </pre>
   *
   * <code>repeated string lanParas = 3;</code>
   */
  int getLanParasCount();
  /**
   * <pre>
   *lan参数
   * </pre>
   *
   * <code>repeated string lanParas = 3;</code>
   */
  java.lang.String getLanParas(int index);
  /**
   * <pre>
   *lan参数
   * </pre>
   *
   * <code>repeated string lanParas = 3;</code>
   */
  com.google.protobuf.ByteString
      getLanParasBytes(int index);

  /**
   * <pre>
   * 数据行唯一ID
   * </pre>
   *
   * <code>required int64 id = 4;</code>
   */
  boolean hasId();
  /**
   * <pre>
   * 数据行唯一ID
   * </pre>
   *
   * <code>required int64 id = 4;</code>
   */
  long getId();
}
