// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface PrepareConscriptionRtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.PrepareConscriptionRt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 rt = 1;</code>
   */
  boolean hasRt();
  /**
   * <code>required int32 rt = 1;</code>
   */
  int getRt();

  /**
   * <pre>
   *当前预征兵数量
   * </pre>
   *
   * <code>optional int32 readySoldier = 2;</code>
   */
  boolean hasReadySoldier();
  /**
   * <pre>
   *当前预征兵数量
   * </pre>
   *
   * <code>optional int32 readySoldier = 2;</code>
   */
  int getReadySoldier();

  /**
   * <pre>
   * 哪个城池的预备兵数量发生了变化
   * </pre>
   *
   * <code>optional int64 cityId = 3;</code>
   */
  boolean hasCityId();
  /**
   * <pre>
   * 哪个城池的预备兵数量发生了变化
   * </pre>
   *
   * <code>optional int64 cityId = 3;</code>
   */
  long getCityId();
}
