// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

/**
 * <pre>
 * msgType = 916
 * 客户端 -&gt; 服务器
 * 查询联盟数据排行榜
 * </pre>
 *
 * Protobuf type {@code client2server.QueryAllianceRank}
 */
public  final class QueryAllianceRank extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:client2server.QueryAllianceRank)
    QueryAllianceRankOrBuilder {
  // Use QueryAllianceRank.newBuilder() to construct.
  private QueryAllianceRank(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryAllianceRank() {
    rankType_ = 0;
    page_ = 0;
    num_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryAllianceRank(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            rankType_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            page_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            num_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pb4client.War2GamePkt.internal_static_client2server_QueryAllianceRank_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pb4client.War2GamePkt.internal_static_client2server_QueryAllianceRank_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pb4client.QueryAllianceRank.class, pb4client.QueryAllianceRank.Builder.class);
  }

  private int bitField0_;
  public static final int RANKTYPE_FIELD_NUMBER = 1;
  private int rankType_;
  /**
   * <pre>
   * 排行榜类型  1-联盟战斗力  2-联盟杀敌数 3-联盟总动员帮派排行榜 4-联盟魔物积分排行
   * </pre>
   *
   * <code>required int32 rankType = 1;</code>
   */
  public boolean hasRankType() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * 排行榜类型  1-联盟战斗力  2-联盟杀敌数 3-联盟总动员帮派排行榜 4-联盟魔物积分排行
   * </pre>
   *
   * <code>required int32 rankType = 1;</code>
   */
  public int getRankType() {
    return rankType_;
  }

  public static final int PAGE_FIELD_NUMBER = 2;
  private int page_;
  /**
   * <code>required int32 page = 2;</code>
   */
  public boolean hasPage() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int32 page = 2;</code>
   */
  public int getPage() {
    return page_;
  }

  public static final int NUM_FIELD_NUMBER = 3;
  private int num_;
  /**
   * <code>required int32 num = 3;</code>
   */
  public boolean hasNum() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required int32 num = 3;</code>
   */
  public int getNum() {
    return num_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasRankType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasPage()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasNum()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, rankType_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, page_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, num_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rankType_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, page_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, num_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pb4client.QueryAllianceRank)) {
      return super.equals(obj);
    }
    pb4client.QueryAllianceRank other = (pb4client.QueryAllianceRank) obj;

    boolean result = true;
    result = result && (hasRankType() == other.hasRankType());
    if (hasRankType()) {
      result = result && (getRankType()
          == other.getRankType());
    }
    result = result && (hasPage() == other.hasPage());
    if (hasPage()) {
      result = result && (getPage()
          == other.getPage());
    }
    result = result && (hasNum() == other.hasNum());
    if (hasNum()) {
      result = result && (getNum()
          == other.getNum());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRankType()) {
      hash = (37 * hash) + RANKTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRankType();
    }
    if (hasPage()) {
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
    }
    if (hasNum()) {
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + getNum();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pb4client.QueryAllianceRank parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4client.QueryAllianceRank parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4client.QueryAllianceRank parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4client.QueryAllianceRank parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4client.QueryAllianceRank parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4client.QueryAllianceRank parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4client.QueryAllianceRank parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb4client.QueryAllianceRank parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb4client.QueryAllianceRank parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pb4client.QueryAllianceRank parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb4client.QueryAllianceRank parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb4client.QueryAllianceRank parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pb4client.QueryAllianceRank prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * msgType = 916
   * 客户端 -&gt; 服务器
   * 查询联盟数据排行榜
   * </pre>
   *
   * Protobuf type {@code client2server.QueryAllianceRank}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:client2server.QueryAllianceRank)
      pb4client.QueryAllianceRankOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb4client.War2GamePkt.internal_static_client2server_QueryAllianceRank_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb4client.War2GamePkt.internal_static_client2server_QueryAllianceRank_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb4client.QueryAllianceRank.class, pb4client.QueryAllianceRank.Builder.class);
    }

    // Construct using pb4client.QueryAllianceRank.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      rankType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      page_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      num_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pb4client.War2GamePkt.internal_static_client2server_QueryAllianceRank_descriptor;
    }

    public pb4client.QueryAllianceRank getDefaultInstanceForType() {
      return pb4client.QueryAllianceRank.getDefaultInstance();
    }

    public pb4client.QueryAllianceRank build() {
      pb4client.QueryAllianceRank result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public pb4client.QueryAllianceRank buildPartial() {
      pb4client.QueryAllianceRank result = new pb4client.QueryAllianceRank(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.rankType_ = rankType_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.page_ = page_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.num_ = num_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pb4client.QueryAllianceRank) {
        return mergeFrom((pb4client.QueryAllianceRank)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pb4client.QueryAllianceRank other) {
      if (other == pb4client.QueryAllianceRank.getDefaultInstance()) return this;
      if (other.hasRankType()) {
        setRankType(other.getRankType());
      }
      if (other.hasPage()) {
        setPage(other.getPage());
      }
      if (other.hasNum()) {
        setNum(other.getNum());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasRankType()) {
        return false;
      }
      if (!hasPage()) {
        return false;
      }
      if (!hasNum()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pb4client.QueryAllianceRank parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pb4client.QueryAllianceRank) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int rankType_ ;
    /**
     * <pre>
     * 排行榜类型  1-联盟战斗力  2-联盟杀敌数 3-联盟总动员帮派排行榜 4-联盟魔物积分排行
     * </pre>
     *
     * <code>required int32 rankType = 1;</code>
     */
    public boolean hasRankType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 排行榜类型  1-联盟战斗力  2-联盟杀敌数 3-联盟总动员帮派排行榜 4-联盟魔物积分排行
     * </pre>
     *
     * <code>required int32 rankType = 1;</code>
     */
    public int getRankType() {
      return rankType_;
    }
    /**
     * <pre>
     * 排行榜类型  1-联盟战斗力  2-联盟杀敌数 3-联盟总动员帮派排行榜 4-联盟魔物积分排行
     * </pre>
     *
     * <code>required int32 rankType = 1;</code>
     */
    public Builder setRankType(int value) {
      bitField0_ |= 0x00000001;
      rankType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 排行榜类型  1-联盟战斗力  2-联盟杀敌数 3-联盟总动员帮派排行榜 4-联盟魔物积分排行
     * </pre>
     *
     * <code>required int32 rankType = 1;</code>
     */
    public Builder clearRankType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rankType_ = 0;
      onChanged();
      return this;
    }

    private int page_ ;
    /**
     * <code>required int32 page = 2;</code>
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 page = 2;</code>
     */
    public int getPage() {
      return page_;
    }
    /**
     * <code>required int32 page = 2;</code>
     */
    public Builder setPage(int value) {
      bitField0_ |= 0x00000002;
      page_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 page = 2;</code>
     */
    public Builder clearPage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      page_ = 0;
      onChanged();
      return this;
    }

    private int num_ ;
    /**
     * <code>required int32 num = 3;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 num = 3;</code>
     */
    public int getNum() {
      return num_;
    }
    /**
     * <code>required int32 num = 3;</code>
     */
    public Builder setNum(int value) {
      bitField0_ |= 0x00000004;
      num_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 num = 3;</code>
     */
    public Builder clearNum() {
      bitField0_ = (bitField0_ & ~0x00000004);
      num_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:client2server.QueryAllianceRank)
  }

  // @@protoc_insertion_point(class_scope:client2server.QueryAllianceRank)
  private static final pb4client.QueryAllianceRank DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pb4client.QueryAllianceRank();
  }

  public static pb4client.QueryAllianceRank getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<QueryAllianceRank>
      PARSER = new com.google.protobuf.AbstractParser<QueryAllianceRank>() {
    public QueryAllianceRank parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryAllianceRank(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryAllianceRank> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryAllianceRank> getParserForType() {
    return PARSER;
  }

  public pb4client.QueryAllianceRank getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

