// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface ReceiveAchievementRewardRtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.ReceiveAchievementRewardRt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 rt = 1;</code>
   */
  boolean hasRt();
  /**
   * <code>required int32 rt = 1;</code>
   */
  int getRt();

  /**
   * <pre>
   *下一阶成就
   * </pre>
   *
   * <code>repeated .client2server.Achievement achieveInfo = 2;</code>
   */
  java.util.List<pb4client.Achievement> 
      getAchieveInfoList();
  /**
   * <pre>
   *下一阶成就
   * </pre>
   *
   * <code>repeated .client2server.Achievement achieveInfo = 2;</code>
   */
  pb4client.Achievement getAchieveInfo(int index);
  /**
   * <pre>
   *下一阶成就
   * </pre>
   *
   * <code>repeated .client2server.Achievement achieveInfo = 2;</code>
   */
  int getAchieveInfoCount();
  /**
   * <pre>
   *下一阶成就
   * </pre>
   *
   * <code>repeated .client2server.Achievement achieveInfo = 2;</code>
   */
  java.util.List<? extends pb4client.AchievementOrBuilder> 
      getAchieveInfoOrBuilderList();
  /**
   * <pre>
   *下一阶成就
   * </pre>
   *
   * <code>repeated .client2server.Achievement achieveInfo = 2;</code>
   */
  pb4client.AchievementOrBuilder getAchieveInfoOrBuilder(
      int index);
}
