// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

/**
 * <pre>
 * msgType = 1051
 * 客户端 -&gt; 服务器
 * 升级科技
 * </pre>
 *
 * Protobuf type {@code client2server.ResearchLvUp}
 */
public  final class ResearchLvUp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:client2server.ResearchLvUp)
    ResearchLvUpOrBuilder {
  // Use ResearchLvUp.newBuilder() to construct.
  private ResearchLvUp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResearchLvUp() {
    researchId_ = 0;
    researchType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResearchLvUp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            researchId_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            researchType_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pb4client.War2GamePkt.internal_static_client2server_ResearchLvUp_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pb4client.War2GamePkt.internal_static_client2server_ResearchLvUp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pb4client.ResearchLvUp.class, pb4client.ResearchLvUp.Builder.class);
  }

  private int bitField0_;
  public static final int RESEARCHID_FIELD_NUMBER = 1;
  private int researchId_;
  /**
   * <pre>
   * 要升级科技的ID 配置表的id字段
   * </pre>
   *
   * <code>required int32 researchId = 1;</code>
   */
  public boolean hasResearchId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * 要升级科技的ID 配置表的id字段
   * </pre>
   *
   * <code>required int32 researchId = 1;</code>
   */
  public int getResearchId() {
    return researchId_;
  }

  public static final int RESEARCHTYPE_FIELD_NUMBER = 2;
  private int researchType_;
  /**
   * <pre>
   * 研发类型  1-普通研发  2-元宝补齐资源研发
   * </pre>
   *
   * <code>required int32 researchType = 2;</code>
   */
  public boolean hasResearchType() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * 研发类型  1-普通研发  2-元宝补齐资源研发
   * </pre>
   *
   * <code>required int32 researchType = 2;</code>
   */
  public int getResearchType() {
    return researchType_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasResearchId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasResearchType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, researchId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, researchType_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, researchId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, researchType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pb4client.ResearchLvUp)) {
      return super.equals(obj);
    }
    pb4client.ResearchLvUp other = (pb4client.ResearchLvUp) obj;

    boolean result = true;
    result = result && (hasResearchId() == other.hasResearchId());
    if (hasResearchId()) {
      result = result && (getResearchId()
          == other.getResearchId());
    }
    result = result && (hasResearchType() == other.hasResearchType());
    if (hasResearchType()) {
      result = result && (getResearchType()
          == other.getResearchType());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResearchId()) {
      hash = (37 * hash) + RESEARCHID_FIELD_NUMBER;
      hash = (53 * hash) + getResearchId();
    }
    if (hasResearchType()) {
      hash = (37 * hash) + RESEARCHTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getResearchType();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pb4client.ResearchLvUp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4client.ResearchLvUp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4client.ResearchLvUp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4client.ResearchLvUp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4client.ResearchLvUp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4client.ResearchLvUp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4client.ResearchLvUp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb4client.ResearchLvUp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb4client.ResearchLvUp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pb4client.ResearchLvUp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb4client.ResearchLvUp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb4client.ResearchLvUp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pb4client.ResearchLvUp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * msgType = 1051
   * 客户端 -&gt; 服务器
   * 升级科技
   * </pre>
   *
   * Protobuf type {@code client2server.ResearchLvUp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:client2server.ResearchLvUp)
      pb4client.ResearchLvUpOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb4client.War2GamePkt.internal_static_client2server_ResearchLvUp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb4client.War2GamePkt.internal_static_client2server_ResearchLvUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb4client.ResearchLvUp.class, pb4client.ResearchLvUp.Builder.class);
    }

    // Construct using pb4client.ResearchLvUp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      researchId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      researchType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pb4client.War2GamePkt.internal_static_client2server_ResearchLvUp_descriptor;
    }

    public pb4client.ResearchLvUp getDefaultInstanceForType() {
      return pb4client.ResearchLvUp.getDefaultInstance();
    }

    public pb4client.ResearchLvUp build() {
      pb4client.ResearchLvUp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public pb4client.ResearchLvUp buildPartial() {
      pb4client.ResearchLvUp result = new pb4client.ResearchLvUp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.researchId_ = researchId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.researchType_ = researchType_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pb4client.ResearchLvUp) {
        return mergeFrom((pb4client.ResearchLvUp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pb4client.ResearchLvUp other) {
      if (other == pb4client.ResearchLvUp.getDefaultInstance()) return this;
      if (other.hasResearchId()) {
        setResearchId(other.getResearchId());
      }
      if (other.hasResearchType()) {
        setResearchType(other.getResearchType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasResearchId()) {
        return false;
      }
      if (!hasResearchType()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pb4client.ResearchLvUp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pb4client.ResearchLvUp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int researchId_ ;
    /**
     * <pre>
     * 要升级科技的ID 配置表的id字段
     * </pre>
     *
     * <code>required int32 researchId = 1;</code>
     */
    public boolean hasResearchId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 要升级科技的ID 配置表的id字段
     * </pre>
     *
     * <code>required int32 researchId = 1;</code>
     */
    public int getResearchId() {
      return researchId_;
    }
    /**
     * <pre>
     * 要升级科技的ID 配置表的id字段
     * </pre>
     *
     * <code>required int32 researchId = 1;</code>
     */
    public Builder setResearchId(int value) {
      bitField0_ |= 0x00000001;
      researchId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 要升级科技的ID 配置表的id字段
     * </pre>
     *
     * <code>required int32 researchId = 1;</code>
     */
    public Builder clearResearchId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      researchId_ = 0;
      onChanged();
      return this;
    }

    private int researchType_ ;
    /**
     * <pre>
     * 研发类型  1-普通研发  2-元宝补齐资源研发
     * </pre>
     *
     * <code>required int32 researchType = 2;</code>
     */
    public boolean hasResearchType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 研发类型  1-普通研发  2-元宝补齐资源研发
     * </pre>
     *
     * <code>required int32 researchType = 2;</code>
     */
    public int getResearchType() {
      return researchType_;
    }
    /**
     * <pre>
     * 研发类型  1-普通研发  2-元宝补齐资源研发
     * </pre>
     *
     * <code>required int32 researchType = 2;</code>
     */
    public Builder setResearchType(int value) {
      bitField0_ |= 0x00000002;
      researchType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 研发类型  1-普通研发  2-元宝补齐资源研发
     * </pre>
     *
     * <code>required int32 researchType = 2;</code>
     */
    public Builder clearResearchType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      researchType_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:client2server.ResearchLvUp)
  }

  // @@protoc_insertion_point(class_scope:client2server.ResearchLvUp)
  private static final pb4client.ResearchLvUp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pb4client.ResearchLvUp();
  }

  public static pb4client.ResearchLvUp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ResearchLvUp>
      PARSER = new com.google.protobuf.AbstractParser<ResearchLvUp>() {
    public ResearchLvUp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResearchLvUp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResearchLvUp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResearchLvUp> getParserForType() {
    return PARSER;
  }

  public pb4client.ResearchLvUp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

