// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface SaveHouseThemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.SaveHouseTheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *主题唯一Id
   * </pre>
   *
   * <code>optional int64 themeId = 1;</code>
   */
  boolean hasThemeId();
  /**
   * <pre>
   *主题唯一Id
   * </pre>
   *
   * <code>optional int64 themeId = 1;</code>
   */
  long getThemeId();

  /**
   * <pre>
   *主题名
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  boolean hasName();
  /**
   * <pre>
   *主题名
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *主题名
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
