// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface SendReinforcePlayerHomeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.SendReinforcePlayerHome)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 groupIds = 1;</code>
   */
  java.util.List<java.lang.Long> getGroupIdsList();
  /**
   * <code>repeated int64 groupIds = 1;</code>
   */
  int getGroupIdsCount();
  /**
   * <code>repeated int64 groupIds = 1;</code>
   */
  long getGroupIds(int index);
}
