// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface SimpleMassInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.SimpleMassInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 集结id
   * </pre>
   *
   * <code>required int64 massId = 1;</code>
   */
  boolean hasMassId();
  /**
   * <pre>
   * 集结id
   * </pre>
   *
   * <code>required int64 massId = 1;</code>
   */
  long getMassId();

  /**
   * <pre>
   * 集结名字
   * </pre>
   *
   * <code>required string massName = 2;</code>
   */
  boolean hasMassName();
  /**
   * <pre>
   * 集结名字
   * </pre>
   *
   * <code>required string massName = 2;</code>
   */
  java.lang.String getMassName();
  /**
   * <pre>
   * 集结名字
   * </pre>
   *
   * <code>required string massName = 2;</code>
   */
  com.google.protobuf.ByteString
      getMassNameBytes();
}
