// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface TaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.Task)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 任务唯一ID
   * </pre>
   *
   * <code>required int64 taskId = 1;</code>
   */
  boolean hasTaskId();
  /**
   * <pre>
   * 任务唯一ID
   * </pre>
   *
   * <code>required int64 taskId = 1;</code>
   */
  long getTaskId();

  /**
   * <pre>
   * 任务模板ID
   * </pre>
   *
   * <code>required int32 taskProtoId = 2;</code>
   */
  boolean hasTaskProtoId();
  /**
   * <pre>
   * 任务模板ID
   * </pre>
   *
   * <code>required int32 taskProtoId = 2;</code>
   */
  int getTaskProtoId();

  /**
   * <pre>
   * 任务状态 0-进行中 1-已完成 2-已领取奖励
   * </pre>
   *
   * <code>required int32 taskState = 3;</code>
   */
  boolean hasTaskState();
  /**
   * <pre>
   * 任务状态 0-进行中 1-已完成 2-已领取奖励
   * </pre>
   *
   * <code>required int32 taskState = 3;</code>
   */
  int getTaskState();

  /**
   * <pre>
   * 任务当前进度
   * </pre>
   *
   * <code>required int64 taskFinish = 4;</code>
   */
  boolean hasTaskFinish();
  /**
   * <pre>
   * 任务当前进度
   * </pre>
   *
   * <code>required int64 taskFinish = 4;</code>
   */
  long getTaskFinish();

  /**
   * <pre>
   * 任务过期时间 -1表示不限时
   * </pre>
   *
   * <code>required int32 overTime = 5;</code>
   */
  boolean hasOverTime();
  /**
   * <pre>
   * 任务过期时间 -1表示不限时
   * </pre>
   *
   * <code>required int32 overTime = 5;</code>
   */
  int getOverTime();
}
