// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

public interface TowerRefreshOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client2server.TowerRefresh)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *当前普通爬塔数据
   * </pre>
   *
   * <code>required string commonTowerInfo = 1;</code>
   */
  boolean hasCommonTowerInfo();
  /**
   * <pre>
   *当前普通爬塔数据
   * </pre>
   *
   * <code>required string commonTowerInfo = 1;</code>
   */
  java.lang.String getCommonTowerInfo();
  /**
   * <pre>
   *当前普通爬塔数据
   * </pre>
   *
   * <code>required string commonTowerInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getCommonTowerInfoBytes();

  /**
   * <pre>
   *当前精英爬塔数据
   * </pre>
   *
   * <code>required string eliteTowerInfo = 2;</code>
   */
  boolean hasEliteTowerInfo();
  /**
   * <pre>
   *当前精英爬塔数据
   * </pre>
   *
   * <code>required string eliteTowerInfo = 2;</code>
   */
  java.lang.String getEliteTowerInfo();
  /**
   * <pre>
   *当前精英爬塔数据
   * </pre>
   *
   * <code>required string eliteTowerInfo = 2;</code>
   */
  com.google.protobuf.ByteString
      getEliteTowerInfoBytes();
}
