// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client2server.proto

package pb4client;

/**
 * <pre>
 * msgType = 15
 * 客户端 -&gt; 服务器
 *新版出征消息
 * </pre>
 *
 * Protobuf type {@code client2server.Walk}
 */
public  final class Walk extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:client2server.Walk)
    WalkOrBuilder {
  // Use Walk.newBuilder() to construct.
  private Walk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Walk() {
    runType_ = 0;
    runTargetType_ = 0;
    aimsX_ = 0;
    aimsY_ = 0;
    heros_ = java.util.Collections.emptyList();
    soliders_ = java.util.Collections.emptyList();
    targetId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Walk(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            runType_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            runTargetType_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            aimsX_ = input.readInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            aimsY_ = input.readInt32();
            break;
          }
          case 40: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              heros_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000010;
            }
            heros_.add(input.readInt64());
            break;
          }
          case 42: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
              heros_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000010;
            }
            while (input.getBytesUntilLimit() > 0) {
              heros_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              soliders_ = new java.util.ArrayList<pb4client.BattleSolider>();
              mutable_bitField0_ |= 0x00000020;
            }
            soliders_.add(
                input.readMessage(pb4client.BattleSolider.PARSER, extensionRegistry));
            break;
          }
          case 56: {
            bitField0_ |= 0x00000010;
            targetId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        heros_ = java.util.Collections.unmodifiableList(heros_);
      }
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        soliders_ = java.util.Collections.unmodifiableList(soliders_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pb4client.War2GamePkt.internal_static_client2server_Walk_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pb4client.War2GamePkt.internal_static_client2server_Walk_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pb4client.Walk.class, pb4client.Walk.Builder.class);
  }

  private int bitField0_;
  public static final int RUNTYPE_FIELD_NUMBER = 1;
  private int runType_;
  /**
   * <pre>
   *打人、打怪、占领地、占领城、运输资源、采集、驻扎、增援、参与集结
   * </pre>
   *
   * <code>required int32 runType = 1;</code>
   */
  public boolean hasRunType() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   *打人、打怪、占领地、占领城、运输资源、采集、驻扎、增援、参与集结
   * </pre>
   *
   * <code>required int32 runType = 1;</code>
   */
  public int getRunType() {
    return runType_;
  }

  public static final int RUNTARGETTYPE_FIELD_NUMBER = 2;
  private int runTargetType_;
  /**
   * <pre>
   *行军目标类型  1-部队 2-军团
   * </pre>
   *
   * <code>required int32 runTargetType = 2;</code>
   */
  public boolean hasRunTargetType() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   *行军目标类型  1-部队 2-军团
   * </pre>
   *
   * <code>required int32 runTargetType = 2;</code>
   */
  public int getRunTargetType() {
    return runTargetType_;
  }

  public static final int AIMSX_FIELD_NUMBER = 3;
  private int aimsX_;
  /**
   * <pre>
   *目的地X
   * </pre>
   *
   * <code>required int32 aimsX = 3;</code>
   */
  public boolean hasAimsX() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   *目的地X
   * </pre>
   *
   * <code>required int32 aimsX = 3;</code>
   */
  public int getAimsX() {
    return aimsX_;
  }

  public static final int AIMSY_FIELD_NUMBER = 4;
  private int aimsY_;
  /**
   * <pre>
   *目的地Y
   * </pre>
   *
   * <code>required int32 aimsY = 4;</code>
   */
  public boolean hasAimsY() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <pre>
   *目的地Y
   * </pre>
   *
   * <code>required int32 aimsY = 4;</code>
   */
  public int getAimsY() {
    return aimsY_;
  }

  public static final int HEROS_FIELD_NUMBER = 5;
  private java.util.List<java.lang.Long> heros_;
  /**
   * <pre>
   *英雄数据
   * </pre>
   *
   * <code>repeated int64 heros = 5;</code>
   */
  public java.util.List<java.lang.Long>
      getHerosList() {
    return heros_;
  }
  /**
   * <pre>
   *英雄数据
   * </pre>
   *
   * <code>repeated int64 heros = 5;</code>
   */
  public int getHerosCount() {
    return heros_.size();
  }
  /**
   * <pre>
   *英雄数据
   * </pre>
   *
   * <code>repeated int64 heros = 5;</code>
   */
  public long getHeros(int index) {
    return heros_.get(index);
  }

  public static final int SOLIDERS_FIELD_NUMBER = 6;
  private java.util.List<pb4client.BattleSolider> soliders_;
  /**
   * <pre>
   *士兵数据
   * </pre>
   *
   * <code>repeated .client2server.BattleSolider soliders = 6;</code>
   */
  public java.util.List<pb4client.BattleSolider> getSolidersList() {
    return soliders_;
  }
  /**
   * <pre>
   *士兵数据
   * </pre>
   *
   * <code>repeated .client2server.BattleSolider soliders = 6;</code>
   */
  public java.util.List<? extends pb4client.BattleSoliderOrBuilder> 
      getSolidersOrBuilderList() {
    return soliders_;
  }
  /**
   * <pre>
   *士兵数据
   * </pre>
   *
   * <code>repeated .client2server.BattleSolider soliders = 6;</code>
   */
  public int getSolidersCount() {
    return soliders_.size();
  }
  /**
   * <pre>
   *士兵数据
   * </pre>
   *
   * <code>repeated .client2server.BattleSolider soliders = 6;</code>
   */
  public pb4client.BattleSolider getSoliders(int index) {
    return soliders_.get(index);
  }
  /**
   * <pre>
   *士兵数据
   * </pre>
   *
   * <code>repeated .client2server.BattleSolider soliders = 6;</code>
   */
  public pb4client.BattleSoliderOrBuilder getSolidersOrBuilder(
      int index) {
    return soliders_.get(index);
  }

  public static final int TARGETID_FIELD_NUMBER = 7;
  private long targetId_;
  /**
   * <pre>
   *目标玩家/集结Id
   * </pre>
   *
   * <code>optional int64 targetId = 7;</code>
   */
  public boolean hasTargetId() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <pre>
   *目标玩家/集结Id
   * </pre>
   *
   * <code>optional int64 targetId = 7;</code>
   */
  public long getTargetId() {
    return targetId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasRunType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasRunTargetType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasAimsX()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasAimsY()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getSolidersCount(); i++) {
      if (!getSoliders(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, runType_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, runTargetType_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, aimsX_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, aimsY_);
    }
    for (int i = 0; i < heros_.size(); i++) {
      output.writeInt64(5, heros_.get(i));
    }
    for (int i = 0; i < soliders_.size(); i++) {
      output.writeMessage(6, soliders_.get(i));
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt64(7, targetId_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, runType_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, runTargetType_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, aimsX_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, aimsY_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < heros_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(heros_.get(i));
      }
      size += dataSize;
      size += 1 * getHerosList().size();
    }
    for (int i = 0; i < soliders_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, soliders_.get(i));
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, targetId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pb4client.Walk)) {
      return super.equals(obj);
    }
    pb4client.Walk other = (pb4client.Walk) obj;

    boolean result = true;
    result = result && (hasRunType() == other.hasRunType());
    if (hasRunType()) {
      result = result && (getRunType()
          == other.getRunType());
    }
    result = result && (hasRunTargetType() == other.hasRunTargetType());
    if (hasRunTargetType()) {
      result = result && (getRunTargetType()
          == other.getRunTargetType());
    }
    result = result && (hasAimsX() == other.hasAimsX());
    if (hasAimsX()) {
      result = result && (getAimsX()
          == other.getAimsX());
    }
    result = result && (hasAimsY() == other.hasAimsY());
    if (hasAimsY()) {
      result = result && (getAimsY()
          == other.getAimsY());
    }
    result = result && getHerosList()
        .equals(other.getHerosList());
    result = result && getSolidersList()
        .equals(other.getSolidersList());
    result = result && (hasTargetId() == other.hasTargetId());
    if (hasTargetId()) {
      result = result && (getTargetId()
          == other.getTargetId());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRunType()) {
      hash = (37 * hash) + RUNTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRunType();
    }
    if (hasRunTargetType()) {
      hash = (37 * hash) + RUNTARGETTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRunTargetType();
    }
    if (hasAimsX()) {
      hash = (37 * hash) + AIMSX_FIELD_NUMBER;
      hash = (53 * hash) + getAimsX();
    }
    if (hasAimsY()) {
      hash = (37 * hash) + AIMSY_FIELD_NUMBER;
      hash = (53 * hash) + getAimsY();
    }
    if (getHerosCount() > 0) {
      hash = (37 * hash) + HEROS_FIELD_NUMBER;
      hash = (53 * hash) + getHerosList().hashCode();
    }
    if (getSolidersCount() > 0) {
      hash = (37 * hash) + SOLIDERS_FIELD_NUMBER;
      hash = (53 * hash) + getSolidersList().hashCode();
    }
    if (hasTargetId()) {
      hash = (37 * hash) + TARGETID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTargetId());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pb4client.Walk parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4client.Walk parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4client.Walk parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4client.Walk parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4client.Walk parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4client.Walk parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4client.Walk parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb4client.Walk parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb4client.Walk parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pb4client.Walk parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb4client.Walk parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb4client.Walk parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pb4client.Walk prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * msgType = 15
   * 客户端 -&gt; 服务器
   *新版出征消息
   * </pre>
   *
   * Protobuf type {@code client2server.Walk}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:client2server.Walk)
      pb4client.WalkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb4client.War2GamePkt.internal_static_client2server_Walk_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb4client.War2GamePkt.internal_static_client2server_Walk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb4client.Walk.class, pb4client.Walk.Builder.class);
    }

    // Construct using pb4client.Walk.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSolidersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      runType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      runTargetType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      aimsX_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      aimsY_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      heros_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);
      if (solidersBuilder_ == null) {
        soliders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        solidersBuilder_.clear();
      }
      targetId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pb4client.War2GamePkt.internal_static_client2server_Walk_descriptor;
    }

    public pb4client.Walk getDefaultInstanceForType() {
      return pb4client.Walk.getDefaultInstance();
    }

    public pb4client.Walk build() {
      pb4client.Walk result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public pb4client.Walk buildPartial() {
      pb4client.Walk result = new pb4client.Walk(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.runType_ = runType_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.runTargetType_ = runTargetType_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.aimsX_ = aimsX_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.aimsY_ = aimsY_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        heros_ = java.util.Collections.unmodifiableList(heros_);
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.heros_ = heros_;
      if (solidersBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          soliders_ = java.util.Collections.unmodifiableList(soliders_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.soliders_ = soliders_;
      } else {
        result.soliders_ = solidersBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000010;
      }
      result.targetId_ = targetId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pb4client.Walk) {
        return mergeFrom((pb4client.Walk)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pb4client.Walk other) {
      if (other == pb4client.Walk.getDefaultInstance()) return this;
      if (other.hasRunType()) {
        setRunType(other.getRunType());
      }
      if (other.hasRunTargetType()) {
        setRunTargetType(other.getRunTargetType());
      }
      if (other.hasAimsX()) {
        setAimsX(other.getAimsX());
      }
      if (other.hasAimsY()) {
        setAimsY(other.getAimsY());
      }
      if (!other.heros_.isEmpty()) {
        if (heros_.isEmpty()) {
          heros_ = other.heros_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureHerosIsMutable();
          heros_.addAll(other.heros_);
        }
        onChanged();
      }
      if (solidersBuilder_ == null) {
        if (!other.soliders_.isEmpty()) {
          if (soliders_.isEmpty()) {
            soliders_ = other.soliders_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureSolidersIsMutable();
            soliders_.addAll(other.soliders_);
          }
          onChanged();
        }
      } else {
        if (!other.soliders_.isEmpty()) {
          if (solidersBuilder_.isEmpty()) {
            solidersBuilder_.dispose();
            solidersBuilder_ = null;
            soliders_ = other.soliders_;
            bitField0_ = (bitField0_ & ~0x00000020);
            solidersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSolidersFieldBuilder() : null;
          } else {
            solidersBuilder_.addAllMessages(other.soliders_);
          }
        }
      }
      if (other.hasTargetId()) {
        setTargetId(other.getTargetId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasRunType()) {
        return false;
      }
      if (!hasRunTargetType()) {
        return false;
      }
      if (!hasAimsX()) {
        return false;
      }
      if (!hasAimsY()) {
        return false;
      }
      for (int i = 0; i < getSolidersCount(); i++) {
        if (!getSoliders(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pb4client.Walk parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pb4client.Walk) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int runType_ ;
    /**
     * <pre>
     *打人、打怪、占领地、占领城、运输资源、采集、驻扎、增援、参与集结
     * </pre>
     *
     * <code>required int32 runType = 1;</code>
     */
    public boolean hasRunType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *打人、打怪、占领地、占领城、运输资源、采集、驻扎、增援、参与集结
     * </pre>
     *
     * <code>required int32 runType = 1;</code>
     */
    public int getRunType() {
      return runType_;
    }
    /**
     * <pre>
     *打人、打怪、占领地、占领城、运输资源、采集、驻扎、增援、参与集结
     * </pre>
     *
     * <code>required int32 runType = 1;</code>
     */
    public Builder setRunType(int value) {
      bitField0_ |= 0x00000001;
      runType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *打人、打怪、占领地、占领城、运输资源、采集、驻扎、增援、参与集结
     * </pre>
     *
     * <code>required int32 runType = 1;</code>
     */
    public Builder clearRunType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      runType_ = 0;
      onChanged();
      return this;
    }

    private int runTargetType_ ;
    /**
     * <pre>
     *行军目标类型  1-部队 2-军团
     * </pre>
     *
     * <code>required int32 runTargetType = 2;</code>
     */
    public boolean hasRunTargetType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *行军目标类型  1-部队 2-军团
     * </pre>
     *
     * <code>required int32 runTargetType = 2;</code>
     */
    public int getRunTargetType() {
      return runTargetType_;
    }
    /**
     * <pre>
     *行军目标类型  1-部队 2-军团
     * </pre>
     *
     * <code>required int32 runTargetType = 2;</code>
     */
    public Builder setRunTargetType(int value) {
      bitField0_ |= 0x00000002;
      runTargetType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *行军目标类型  1-部队 2-军团
     * </pre>
     *
     * <code>required int32 runTargetType = 2;</code>
     */
    public Builder clearRunTargetType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      runTargetType_ = 0;
      onChanged();
      return this;
    }

    private int aimsX_ ;
    /**
     * <pre>
     *目的地X
     * </pre>
     *
     * <code>required int32 aimsX = 3;</code>
     */
    public boolean hasAimsX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *目的地X
     * </pre>
     *
     * <code>required int32 aimsX = 3;</code>
     */
    public int getAimsX() {
      return aimsX_;
    }
    /**
     * <pre>
     *目的地X
     * </pre>
     *
     * <code>required int32 aimsX = 3;</code>
     */
    public Builder setAimsX(int value) {
      bitField0_ |= 0x00000004;
      aimsX_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目的地X
     * </pre>
     *
     * <code>required int32 aimsX = 3;</code>
     */
    public Builder clearAimsX() {
      bitField0_ = (bitField0_ & ~0x00000004);
      aimsX_ = 0;
      onChanged();
      return this;
    }

    private int aimsY_ ;
    /**
     * <pre>
     *目的地Y
     * </pre>
     *
     * <code>required int32 aimsY = 4;</code>
     */
    public boolean hasAimsY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *目的地Y
     * </pre>
     *
     * <code>required int32 aimsY = 4;</code>
     */
    public int getAimsY() {
      return aimsY_;
    }
    /**
     * <pre>
     *目的地Y
     * </pre>
     *
     * <code>required int32 aimsY = 4;</code>
     */
    public Builder setAimsY(int value) {
      bitField0_ |= 0x00000008;
      aimsY_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目的地Y
     * </pre>
     *
     * <code>required int32 aimsY = 4;</code>
     */
    public Builder clearAimsY() {
      bitField0_ = (bitField0_ & ~0x00000008);
      aimsY_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Long> heros_ = java.util.Collections.emptyList();
    private void ensureHerosIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        heros_ = new java.util.ArrayList<java.lang.Long>(heros_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <pre>
     *英雄数据
     * </pre>
     *
     * <code>repeated int64 heros = 5;</code>
     */
    public java.util.List<java.lang.Long>
        getHerosList() {
      return java.util.Collections.unmodifiableList(heros_);
    }
    /**
     * <pre>
     *英雄数据
     * </pre>
     *
     * <code>repeated int64 heros = 5;</code>
     */
    public int getHerosCount() {
      return heros_.size();
    }
    /**
     * <pre>
     *英雄数据
     * </pre>
     *
     * <code>repeated int64 heros = 5;</code>
     */
    public long getHeros(int index) {
      return heros_.get(index);
    }
    /**
     * <pre>
     *英雄数据
     * </pre>
     *
     * <code>repeated int64 heros = 5;</code>
     */
    public Builder setHeros(
        int index, long value) {
      ensureHerosIsMutable();
      heros_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *英雄数据
     * </pre>
     *
     * <code>repeated int64 heros = 5;</code>
     */
    public Builder addHeros(long value) {
      ensureHerosIsMutable();
      heros_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *英雄数据
     * </pre>
     *
     * <code>repeated int64 heros = 5;</code>
     */
    public Builder addAllHeros(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureHerosIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, heros_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *英雄数据
     * </pre>
     *
     * <code>repeated int64 heros = 5;</code>
     */
    public Builder clearHeros() {
      heros_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    private java.util.List<pb4client.BattleSolider> soliders_ =
      java.util.Collections.emptyList();
    private void ensureSolidersIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        soliders_ = new java.util.ArrayList<pb4client.BattleSolider>(soliders_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        pb4client.BattleSolider, pb4client.BattleSolider.Builder, pb4client.BattleSoliderOrBuilder> solidersBuilder_;

    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public java.util.List<pb4client.BattleSolider> getSolidersList() {
      if (solidersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(soliders_);
      } else {
        return solidersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public int getSolidersCount() {
      if (solidersBuilder_ == null) {
        return soliders_.size();
      } else {
        return solidersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public pb4client.BattleSolider getSoliders(int index) {
      if (solidersBuilder_ == null) {
        return soliders_.get(index);
      } else {
        return solidersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public Builder setSoliders(
        int index, pb4client.BattleSolider value) {
      if (solidersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSolidersIsMutable();
        soliders_.set(index, value);
        onChanged();
      } else {
        solidersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public Builder setSoliders(
        int index, pb4client.BattleSolider.Builder builderForValue) {
      if (solidersBuilder_ == null) {
        ensureSolidersIsMutable();
        soliders_.set(index, builderForValue.build());
        onChanged();
      } else {
        solidersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public Builder addSoliders(pb4client.BattleSolider value) {
      if (solidersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSolidersIsMutable();
        soliders_.add(value);
        onChanged();
      } else {
        solidersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public Builder addSoliders(
        int index, pb4client.BattleSolider value) {
      if (solidersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSolidersIsMutable();
        soliders_.add(index, value);
        onChanged();
      } else {
        solidersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public Builder addSoliders(
        pb4client.BattleSolider.Builder builderForValue) {
      if (solidersBuilder_ == null) {
        ensureSolidersIsMutable();
        soliders_.add(builderForValue.build());
        onChanged();
      } else {
        solidersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public Builder addSoliders(
        int index, pb4client.BattleSolider.Builder builderForValue) {
      if (solidersBuilder_ == null) {
        ensureSolidersIsMutable();
        soliders_.add(index, builderForValue.build());
        onChanged();
      } else {
        solidersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public Builder addAllSoliders(
        java.lang.Iterable<? extends pb4client.BattleSolider> values) {
      if (solidersBuilder_ == null) {
        ensureSolidersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, soliders_);
        onChanged();
      } else {
        solidersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public Builder clearSoliders() {
      if (solidersBuilder_ == null) {
        soliders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        solidersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public Builder removeSoliders(int index) {
      if (solidersBuilder_ == null) {
        ensureSolidersIsMutable();
        soliders_.remove(index);
        onChanged();
      } else {
        solidersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public pb4client.BattleSolider.Builder getSolidersBuilder(
        int index) {
      return getSolidersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public pb4client.BattleSoliderOrBuilder getSolidersOrBuilder(
        int index) {
      if (solidersBuilder_ == null) {
        return soliders_.get(index);  } else {
        return solidersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public java.util.List<? extends pb4client.BattleSoliderOrBuilder> 
         getSolidersOrBuilderList() {
      if (solidersBuilder_ != null) {
        return solidersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(soliders_);
      }
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public pb4client.BattleSolider.Builder addSolidersBuilder() {
      return getSolidersFieldBuilder().addBuilder(
          pb4client.BattleSolider.getDefaultInstance());
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public pb4client.BattleSolider.Builder addSolidersBuilder(
        int index) {
      return getSolidersFieldBuilder().addBuilder(
          index, pb4client.BattleSolider.getDefaultInstance());
    }
    /**
     * <pre>
     *士兵数据
     * </pre>
     *
     * <code>repeated .client2server.BattleSolider soliders = 6;</code>
     */
    public java.util.List<pb4client.BattleSolider.Builder> 
         getSolidersBuilderList() {
      return getSolidersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        pb4client.BattleSolider, pb4client.BattleSolider.Builder, pb4client.BattleSoliderOrBuilder> 
        getSolidersFieldBuilder() {
      if (solidersBuilder_ == null) {
        solidersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            pb4client.BattleSolider, pb4client.BattleSolider.Builder, pb4client.BattleSoliderOrBuilder>(
                soliders_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        soliders_ = null;
      }
      return solidersBuilder_;
    }

    private long targetId_ ;
    /**
     * <pre>
     *目标玩家/集结Id
     * </pre>
     *
     * <code>optional int64 targetId = 7;</code>
     */
    public boolean hasTargetId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     *目标玩家/集结Id
     * </pre>
     *
     * <code>optional int64 targetId = 7;</code>
     */
    public long getTargetId() {
      return targetId_;
    }
    /**
     * <pre>
     *目标玩家/集结Id
     * </pre>
     *
     * <code>optional int64 targetId = 7;</code>
     */
    public Builder setTargetId(long value) {
      bitField0_ |= 0x00000040;
      targetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目标玩家/集结Id
     * </pre>
     *
     * <code>optional int64 targetId = 7;</code>
     */
    public Builder clearTargetId() {
      bitField0_ = (bitField0_ & ~0x00000040);
      targetId_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:client2server.Walk)
  }

  // @@protoc_insertion_point(class_scope:client2server.Walk)
  private static final pb4client.Walk DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pb4client.Walk();
  }

  public static pb4client.Walk getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Walk>
      PARSER = new com.google.protobuf.AbstractParser<Walk>() {
    public Walk parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Walk(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Walk> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Walk> getParserForType() {
    return PARSER;
  }

  public pb4client.Walk getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

