// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal2public.proto

package pb4server;

public interface AllianceQueryTopicAskRtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb4server.AllianceQueryTopicAskRt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rt = 1;</code>
   */
  int getRt();

  /**
   * <pre>
   *联盟邮件的主题及回复记录（部分回复记录）
   * </pre>
   *
   * <code>repeated .pb4server.AllianceTopicInfoVo topics = 2;</code>
   */
  java.util.List<pb4server.AllianceTopicInfoVo> 
      getTopicsList();
  /**
   * <pre>
   *联盟邮件的主题及回复记录（部分回复记录）
   * </pre>
   *
   * <code>repeated .pb4server.AllianceTopicInfoVo topics = 2;</code>
   */
  pb4server.AllianceTopicInfoVo getTopics(int index);
  /**
   * <pre>
   *联盟邮件的主题及回复记录（部分回复记录）
   * </pre>
   *
   * <code>repeated .pb4server.AllianceTopicInfoVo topics = 2;</code>
   */
  int getTopicsCount();
  /**
   * <pre>
   *联盟邮件的主题及回复记录（部分回复记录）
   * </pre>
   *
   * <code>repeated .pb4server.AllianceTopicInfoVo topics = 2;</code>
   */
  java.util.List<? extends pb4server.AllianceTopicInfoVoOrBuilder> 
      getTopicsOrBuilderList();
  /**
   * <pre>
   *联盟邮件的主题及回复记录（部分回复记录）
   * </pre>
   *
   * <code>repeated .pb4server.AllianceTopicInfoVo topics = 2;</code>
   */
  pb4server.AllianceTopicInfoVoOrBuilder getTopicsOrBuilder(
      int index);
}
