// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal2public.proto

package pb4server;

public interface AllianceHelpVoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb4server.AllianceHelpVo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 帮助信息的唯一ID
   * </pre>
   *
   * <code>int64 helpId = 1;</code>
   */
  long getHelpId();

  /**
   * <pre>
   * 帮助类型  1-研发帮助
   * </pre>
   *
   * <code>int32 helpType = 2;</code>
   */
  int getHelpType();

  /**
   * <pre>
   * 上限帮助次数
   * </pre>
   *
   * <code>int32 maxHelpNum = 3;</code>
   */
  int getMaxHelpNum();

  /**
   * <pre>
   * 当前帮助次数
   * </pre>
   *
   * <code>int32 nowHelpNum = 4;</code>
   */
  int getNowHelpNum();

  /**
   * <pre>
   * 需要帮助的玩家ID
   * </pre>
   *
   * <code>int64 helpPlayerId = 5;</code>
   */
  long getHelpPlayerId();

  /**
   * <pre>
   * 需要帮助的玩家名
   * </pre>
   *
   * <code>string helpPlayerName = 6;</code>
   */
  java.lang.String getHelpPlayerName();
  /**
   * <pre>
   * 需要帮助的玩家名
   * </pre>
   *
   * <code>string helpPlayerName = 6;</code>
   */
  com.google.protobuf.ByteString
      getHelpPlayerNameBytes();

  /**
   * <pre>
   * 信息1  对于不同的帮助类型有不同的意义,如 研发帮助 这个字段表示科技ID
   * </pre>
   *
   * <code>int64 helpValue1 = 7;</code>
   */
  long getHelpValue1();

  /**
   * <pre>
   * 信息2  对于不同的帮助类型有不同的意义,如 研发帮助 这个字段表示科技等级
   * </pre>
   *
   * <code>int64 helpValue2 = 8;</code>
   */
  long getHelpValue2();

  /**
   * <pre>
   * 信息3  对于不同的帮助类型有不同的意义,如 研发帮助 这个字段暂无意义,预留
   * </pre>
   *
   * <code>int64 helpValue3 = 9;</code>
   */
  long getHelpValue3();

  /**
   * <pre>
   * 信息4  对于不同的帮助类型有不同的意义,如 研发帮助 这个字段暂无意义,预留
   * </pre>
   *
   * <code>int64 helpValue4 = 10;</code>
   */
  long getHelpValue4();

  /**
   * <pre>
   * 玩家头像
   * </pre>
   *
   * <code>int32 photoId = 11;</code>
   */
  int getPhotoId();
}
