// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal2public.proto

package pb4server;

/**
 * Protobuf type {@code pb4server.ChatInfoVo}
 */
public  final class ChatInfoVo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb4server.ChatInfoVo)
    ChatInfoVoOrBuilder {
  // Use ChatInfoVo.newBuilder() to construct.
  private ChatInfoVo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatInfoVo() {
    type_ = 0;
    isSystem_ = 0;
    country_ = 0;
    allianceName_ = "";
    allianceShortName_ = "";
    alliancePositions_ = "";
    player_ = "";
    playerShortName_ = "";
    playerIcon_ = 0;
    sendTime_ = 0;
    id_ = 0L;
    playerId_ = 0L;
    messageType_ = 0;
    office_ = 0;
    vipLv_ = 0;
    areaNo_ = 0;
    chatRoomId_ = 0L;
    talkToId_ = 0L;
    x_ = 0;
    y_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ChatInfoVo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            type_ = input.readInt32();
            break;
          }
          case 16: {

            isSystem_ = input.readInt32();
            break;
          }
          case 24: {

            country_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            allianceName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            allianceShortName_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            alliancePositions_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            player_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            playerShortName_ = s;
            break;
          }
          case 72: {

            playerIcon_ = input.readInt32();
            break;
          }
          case 82: {
            pb4server.NoticeVo.Builder subBuilder = null;
            if (message_ != null) {
              subBuilder = message_.toBuilder();
            }
            message_ = input.readMessage(pb4server.NoticeVo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(message_);
              message_ = subBuilder.buildPartial();
            }

            break;
          }
          case 88: {

            sendTime_ = input.readInt32();
            break;
          }
          case 96: {

            id_ = input.readInt64();
            break;
          }
          case 104: {

            playerId_ = input.readInt64();
            break;
          }
          case 112: {

            messageType_ = input.readInt32();
            break;
          }
          case 120: {

            office_ = input.readInt32();
            break;
          }
          case 128: {

            vipLv_ = input.readInt32();
            break;
          }
          case 136: {

            areaNo_ = input.readInt32();
            break;
          }
          case 146: {
            pb4server.SimpleFightReportVo.Builder subBuilder = null;
            if (easyFightInfo_ != null) {
              subBuilder = easyFightInfo_.toBuilder();
            }
            easyFightInfo_ = input.readMessage(pb4server.SimpleFightReportVo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(easyFightInfo_);
              easyFightInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 154: {
            pb4server.SimpleMassInfoVo.Builder subBuilder = null;
            if (massInfo_ != null) {
              subBuilder = massInfo_.toBuilder();
            }
            massInfo_ = input.readMessage(pb4server.SimpleMassInfoVo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(massInfo_);
              massInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 160: {

            chatRoomId_ = input.readInt64();
            break;
          }
          case 168: {

            talkToId_ = input.readInt64();
            break;
          }
          case 176: {

            x_ = input.readInt32();
            break;
          }
          case 184: {

            y_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pb4server.InternalPkt.internal_static_pb4server_ChatInfoVo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pb4server.InternalPkt.internal_static_pb4server_ChatInfoVo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pb4server.ChatInfoVo.class, pb4server.ChatInfoVo.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <pre>
   *  聊天频道   0世界 1国家 2联盟 3跟好友聊天  4群聊
   * </pre>
   *
   * <code>int32 type = 1;</code>
   */
  public int getType() {
    return type_;
  }

  public static final int ISSYSTEM_FIELD_NUMBER = 2;
  private int isSystem_;
  /**
   * <pre>
   * 是否是系统发布:0-玩家发布  1-系统发布
   * </pre>
   *
   * <code>int32 isSystem = 2;</code>
   */
  public int getIsSystem() {
    return isSystem_;
  }

  public static final int COUNTRY_FIELD_NUMBER = 3;
  private int country_;
  /**
   * <pre>
   * 真实国家
   * </pre>
   *
   * <code>int32 country = 3;</code>
   */
  public int getCountry() {
    return country_;
  }

  public static final int ALLIANCENAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object allianceName_;
  /**
   * <pre>
   * 联盟名称
   * </pre>
   *
   * <code>string allianceName = 4;</code>
   */
  public java.lang.String getAllianceName() {
    java.lang.Object ref = allianceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      allianceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 联盟名称
   * </pre>
   *
   * <code>string allianceName = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAllianceNameBytes() {
    java.lang.Object ref = allianceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      allianceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALLIANCESHORTNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object allianceShortName_;
  /**
   * <pre>
   * 联盟简称
   * </pre>
   *
   * <code>string allianceShortName = 5;</code>
   */
  public java.lang.String getAllianceShortName() {
    java.lang.Object ref = allianceShortName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      allianceShortName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 联盟简称
   * </pre>
   *
   * <code>string allianceShortName = 5;</code>
   */
  public com.google.protobuf.ByteString
      getAllianceShortNameBytes() {
    java.lang.Object ref = allianceShortName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      allianceShortName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALLIANCEPOSITIONS_FIELD_NUMBER = 6;
  private volatile java.lang.Object alliancePositions_;
  /**
   * <pre>
   * 所属联盟官位
   * </pre>
   *
   * <code>string alliancePositions = 6;</code>
   */
  public java.lang.String getAlliancePositions() {
    java.lang.Object ref = alliancePositions_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alliancePositions_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 所属联盟官位
   * </pre>
   *
   * <code>string alliancePositions = 6;</code>
   */
  public com.google.protobuf.ByteString
      getAlliancePositionsBytes() {
    java.lang.Object ref = alliancePositions_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alliancePositions_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYER_FIELD_NUMBER = 7;
  private volatile java.lang.Object player_;
  /**
   * <pre>
   * 说话者名字
   * </pre>
   *
   * <code>string player = 7;</code>
   */
  public java.lang.String getPlayer() {
    java.lang.Object ref = player_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      player_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 说话者名字
   * </pre>
   *
   * <code>string player = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPlayerBytes() {
    java.lang.Object ref = player_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      player_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYERSHORTNAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object playerShortName_;
  /**
   * <pre>
   * 玩家昵称
   * </pre>
   *
   * <code>string playerShortName = 8;</code>
   */
  public java.lang.String getPlayerShortName() {
    java.lang.Object ref = playerShortName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      playerShortName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 玩家昵称
   * </pre>
   *
   * <code>string playerShortName = 8;</code>
   */
  public com.google.protobuf.ByteString
      getPlayerShortNameBytes() {
    java.lang.Object ref = playerShortName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      playerShortName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYERICON_FIELD_NUMBER = 9;
  private int playerIcon_;
  /**
   * <pre>
   * 头像模板id
   * </pre>
   *
   * <code>int32 playerIcon = 9;</code>
   */
  public int getPlayerIcon() {
    return playerIcon_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 10;
  private pb4server.NoticeVo message_;
  /**
   * <pre>
   * 内容
   * </pre>
   *
   * <code>.pb4server.NoticeVo message = 10;</code>
   */
  public boolean hasMessage() {
    return message_ != null;
  }
  /**
   * <pre>
   * 内容
   * </pre>
   *
   * <code>.pb4server.NoticeVo message = 10;</code>
   */
  public pb4server.NoticeVo getMessage() {
    return message_ == null ? pb4server.NoticeVo.getDefaultInstance() : message_;
  }
  /**
   * <pre>
   * 内容
   * </pre>
   *
   * <code>.pb4server.NoticeVo message = 10;</code>
   */
  public pb4server.NoticeVoOrBuilder getMessageOrBuilder() {
    return getMessage();
  }

  public static final int SENDTIME_FIELD_NUMBER = 11;
  private int sendTime_;
  /**
   * <pre>
   * 发送时间
   * </pre>
   *
   * <code>int32 sendTime = 11;</code>
   */
  public int getSendTime() {
    return sendTime_;
  }

  public static final int ID_FIELD_NUMBER = 12;
  private long id_;
  /**
   * <pre>
   * 唯一ID
   * </pre>
   *
   * <code>int64 id = 12;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int PLAYERID_FIELD_NUMBER = 13;
  private long playerId_;
  /**
   * <pre>
   * 玩家ID
   * </pre>
   *
   * <code>int64 playerId = 13;</code>
   */
  public long getPlayerId() {
    return playerId_;
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 14;
  private int messageType_;
  /**
   * <pre>
   * 消息类型  1-普通消息  2-红包消息（暂时被砍） 3-表情  4-战报分享  5-集结  6-喇叭 7-坐标
   * </pre>
   *
   * <code>int32 messageType = 14;</code>
   */
  public int getMessageType() {
    return messageType_;
  }

  public static final int OFFICE_FIELD_NUMBER = 15;
  private int office_;
  /**
   * <pre>
   *官职Id
   * </pre>
   *
   * <code>int32 office = 15;</code>
   */
  public int getOffice() {
    return office_;
  }

  public static final int VIPLV_FIELD_NUMBER = 16;
  private int vipLv_;
  /**
   * <pre>
   * vip等级
   * </pre>
   *
   * <code>int32 vipLv = 16;</code>
   */
  public int getVipLv() {
    return vipLv_;
  }

  public static final int AREANO_FIELD_NUMBER = 17;
  private int areaNo_;
  /**
   * <pre>
   * 服务器编号
   * </pre>
   *
   * <code>int32 areaNo = 17;</code>
   */
  public int getAreaNo() {
    return areaNo_;
  }

  public static final int EASYFIGHTINFO_FIELD_NUMBER = 18;
  private pb4server.SimpleFightReportVo easyFightInfo_;
  /**
   * <pre>
   * 战报分享
   * </pre>
   *
   * <code>.pb4server.SimpleFightReportVo easyFightInfo = 18;</code>
   */
  public boolean hasEasyFightInfo() {
    return easyFightInfo_ != null;
  }
  /**
   * <pre>
   * 战报分享
   * </pre>
   *
   * <code>.pb4server.SimpleFightReportVo easyFightInfo = 18;</code>
   */
  public pb4server.SimpleFightReportVo getEasyFightInfo() {
    return easyFightInfo_ == null ? pb4server.SimpleFightReportVo.getDefaultInstance() : easyFightInfo_;
  }
  /**
   * <pre>
   * 战报分享
   * </pre>
   *
   * <code>.pb4server.SimpleFightReportVo easyFightInfo = 18;</code>
   */
  public pb4server.SimpleFightReportVoOrBuilder getEasyFightInfoOrBuilder() {
    return getEasyFightInfo();
  }

  public static final int MASSINFO_FIELD_NUMBER = 19;
  private pb4server.SimpleMassInfoVo massInfo_;
  /**
   * <pre>
   * 集结信息
   * </pre>
   *
   * <code>.pb4server.SimpleMassInfoVo massInfo = 19;</code>
   */
  public boolean hasMassInfo() {
    return massInfo_ != null;
  }
  /**
   * <pre>
   * 集结信息
   * </pre>
   *
   * <code>.pb4server.SimpleMassInfoVo massInfo = 19;</code>
   */
  public pb4server.SimpleMassInfoVo getMassInfo() {
    return massInfo_ == null ? pb4server.SimpleMassInfoVo.getDefaultInstance() : massInfo_;
  }
  /**
   * <pre>
   * 集结信息
   * </pre>
   *
   * <code>.pb4server.SimpleMassInfoVo massInfo = 19;</code>
   */
  public pb4server.SimpleMassInfoVoOrBuilder getMassInfoOrBuilder() {
    return getMassInfo();
  }

  public static final int CHATROOMID_FIELD_NUMBER = 20;
  private long chatRoomId_;
  /**
   * <pre>
   * 聊天室Id
   * </pre>
   *
   * <code>int64 chatRoomId = 20;</code>
   */
  public long getChatRoomId() {
    return chatRoomId_;
  }

  public static final int TALKTOID_FIELD_NUMBER = 21;
  private long talkToId_;
  /**
   * <pre>
   * 我的聊天对象id
   * </pre>
   *
   * <code>int64 talkToId = 21;</code>
   */
  public long getTalkToId() {
    return talkToId_;
  }

  public static final int X_FIELD_NUMBER = 22;
  private int x_;
  /**
   * <pre>
   * 坐标x
   * </pre>
   *
   * <code>int32 x = 22;</code>
   */
  public int getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 23;
  private int y_;
  /**
   * <pre>
   * 坐标y
   * </pre>
   *
   * <code>int32 y = 23;</code>
   */
  public int getY() {
    return y_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != 0) {
      output.writeInt32(1, type_);
    }
    if (isSystem_ != 0) {
      output.writeInt32(2, isSystem_);
    }
    if (country_ != 0) {
      output.writeInt32(3, country_);
    }
    if (!getAllianceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, allianceName_);
    }
    if (!getAllianceShortNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, allianceShortName_);
    }
    if (!getAlliancePositionsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, alliancePositions_);
    }
    if (!getPlayerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, player_);
    }
    if (!getPlayerShortNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, playerShortName_);
    }
    if (playerIcon_ != 0) {
      output.writeInt32(9, playerIcon_);
    }
    if (message_ != null) {
      output.writeMessage(10, getMessage());
    }
    if (sendTime_ != 0) {
      output.writeInt32(11, sendTime_);
    }
    if (id_ != 0L) {
      output.writeInt64(12, id_);
    }
    if (playerId_ != 0L) {
      output.writeInt64(13, playerId_);
    }
    if (messageType_ != 0) {
      output.writeInt32(14, messageType_);
    }
    if (office_ != 0) {
      output.writeInt32(15, office_);
    }
    if (vipLv_ != 0) {
      output.writeInt32(16, vipLv_);
    }
    if (areaNo_ != 0) {
      output.writeInt32(17, areaNo_);
    }
    if (easyFightInfo_ != null) {
      output.writeMessage(18, getEasyFightInfo());
    }
    if (massInfo_ != null) {
      output.writeMessage(19, getMassInfo());
    }
    if (chatRoomId_ != 0L) {
      output.writeInt64(20, chatRoomId_);
    }
    if (talkToId_ != 0L) {
      output.writeInt64(21, talkToId_);
    }
    if (x_ != 0) {
      output.writeInt32(22, x_);
    }
    if (y_ != 0) {
      output.writeInt32(23, y_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, type_);
    }
    if (isSystem_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, isSystem_);
    }
    if (country_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, country_);
    }
    if (!getAllianceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, allianceName_);
    }
    if (!getAllianceShortNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, allianceShortName_);
    }
    if (!getAlliancePositionsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, alliancePositions_);
    }
    if (!getPlayerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, player_);
    }
    if (!getPlayerShortNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, playerShortName_);
    }
    if (playerIcon_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, playerIcon_);
    }
    if (message_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getMessage());
    }
    if (sendTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, sendTime_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, id_);
    }
    if (playerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, playerId_);
    }
    if (messageType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, messageType_);
    }
    if (office_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, office_);
    }
    if (vipLv_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, vipLv_);
    }
    if (areaNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, areaNo_);
    }
    if (easyFightInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(18, getEasyFightInfo());
    }
    if (massInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(19, getMassInfo());
    }
    if (chatRoomId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(20, chatRoomId_);
    }
    if (talkToId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(21, talkToId_);
    }
    if (x_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(22, x_);
    }
    if (y_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(23, y_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pb4server.ChatInfoVo)) {
      return super.equals(obj);
    }
    pb4server.ChatInfoVo other = (pb4server.ChatInfoVo) obj;

    boolean result = true;
    result = result && (getType()
        == other.getType());
    result = result && (getIsSystem()
        == other.getIsSystem());
    result = result && (getCountry()
        == other.getCountry());
    result = result && getAllianceName()
        .equals(other.getAllianceName());
    result = result && getAllianceShortName()
        .equals(other.getAllianceShortName());
    result = result && getAlliancePositions()
        .equals(other.getAlliancePositions());
    result = result && getPlayer()
        .equals(other.getPlayer());
    result = result && getPlayerShortName()
        .equals(other.getPlayerShortName());
    result = result && (getPlayerIcon()
        == other.getPlayerIcon());
    result = result && (hasMessage() == other.hasMessage());
    if (hasMessage()) {
      result = result && getMessage()
          .equals(other.getMessage());
    }
    result = result && (getSendTime()
        == other.getSendTime());
    result = result && (getId()
        == other.getId());
    result = result && (getPlayerId()
        == other.getPlayerId());
    result = result && (getMessageType()
        == other.getMessageType());
    result = result && (getOffice()
        == other.getOffice());
    result = result && (getVipLv()
        == other.getVipLv());
    result = result && (getAreaNo()
        == other.getAreaNo());
    result = result && (hasEasyFightInfo() == other.hasEasyFightInfo());
    if (hasEasyFightInfo()) {
      result = result && getEasyFightInfo()
          .equals(other.getEasyFightInfo());
    }
    result = result && (hasMassInfo() == other.hasMassInfo());
    if (hasMassInfo()) {
      result = result && getMassInfo()
          .equals(other.getMassInfo());
    }
    result = result && (getChatRoomId()
        == other.getChatRoomId());
    result = result && (getTalkToId()
        == other.getTalkToId());
    result = result && (getX()
        == other.getX());
    result = result && (getY()
        == other.getY());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + ISSYSTEM_FIELD_NUMBER;
    hash = (53 * hash) + getIsSystem();
    hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
    hash = (53 * hash) + getCountry();
    hash = (37 * hash) + ALLIANCENAME_FIELD_NUMBER;
    hash = (53 * hash) + getAllianceName().hashCode();
    hash = (37 * hash) + ALLIANCESHORTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAllianceShortName().hashCode();
    hash = (37 * hash) + ALLIANCEPOSITIONS_FIELD_NUMBER;
    hash = (53 * hash) + getAlliancePositions().hashCode();
    hash = (37 * hash) + PLAYER_FIELD_NUMBER;
    hash = (53 * hash) + getPlayer().hashCode();
    hash = (37 * hash) + PLAYERSHORTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerShortName().hashCode();
    hash = (37 * hash) + PLAYERICON_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerIcon();
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + getSendTime();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPlayerId());
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMessageType();
    hash = (37 * hash) + OFFICE_FIELD_NUMBER;
    hash = (53 * hash) + getOffice();
    hash = (37 * hash) + VIPLV_FIELD_NUMBER;
    hash = (53 * hash) + getVipLv();
    hash = (37 * hash) + AREANO_FIELD_NUMBER;
    hash = (53 * hash) + getAreaNo();
    if (hasEasyFightInfo()) {
      hash = (37 * hash) + EASYFIGHTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getEasyFightInfo().hashCode();
    }
    if (hasMassInfo()) {
      hash = (37 * hash) + MASSINFO_FIELD_NUMBER;
      hash = (53 * hash) + getMassInfo().hashCode();
    }
    hash = (37 * hash) + CHATROOMID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getChatRoomId());
    hash = (37 * hash) + TALKTOID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTalkToId());
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + getX();
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + getY();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pb4server.ChatInfoVo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4server.ChatInfoVo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4server.ChatInfoVo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4server.ChatInfoVo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4server.ChatInfoVo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4server.ChatInfoVo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4server.ChatInfoVo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb4server.ChatInfoVo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb4server.ChatInfoVo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pb4server.ChatInfoVo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb4server.ChatInfoVo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb4server.ChatInfoVo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pb4server.ChatInfoVo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb4server.ChatInfoVo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb4server.ChatInfoVo)
      pb4server.ChatInfoVoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb4server.InternalPkt.internal_static_pb4server_ChatInfoVo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb4server.InternalPkt.internal_static_pb4server_ChatInfoVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb4server.ChatInfoVo.class, pb4server.ChatInfoVo.Builder.class);
    }

    // Construct using pb4server.ChatInfoVo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      isSystem_ = 0;

      country_ = 0;

      allianceName_ = "";

      allianceShortName_ = "";

      alliancePositions_ = "";

      player_ = "";

      playerShortName_ = "";

      playerIcon_ = 0;

      if (messageBuilder_ == null) {
        message_ = null;
      } else {
        message_ = null;
        messageBuilder_ = null;
      }
      sendTime_ = 0;

      id_ = 0L;

      playerId_ = 0L;

      messageType_ = 0;

      office_ = 0;

      vipLv_ = 0;

      areaNo_ = 0;

      if (easyFightInfoBuilder_ == null) {
        easyFightInfo_ = null;
      } else {
        easyFightInfo_ = null;
        easyFightInfoBuilder_ = null;
      }
      if (massInfoBuilder_ == null) {
        massInfo_ = null;
      } else {
        massInfo_ = null;
        massInfoBuilder_ = null;
      }
      chatRoomId_ = 0L;

      talkToId_ = 0L;

      x_ = 0;

      y_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pb4server.InternalPkt.internal_static_pb4server_ChatInfoVo_descriptor;
    }

    public pb4server.ChatInfoVo getDefaultInstanceForType() {
      return pb4server.ChatInfoVo.getDefaultInstance();
    }

    public pb4server.ChatInfoVo build() {
      pb4server.ChatInfoVo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public pb4server.ChatInfoVo buildPartial() {
      pb4server.ChatInfoVo result = new pb4server.ChatInfoVo(this);
      result.type_ = type_;
      result.isSystem_ = isSystem_;
      result.country_ = country_;
      result.allianceName_ = allianceName_;
      result.allianceShortName_ = allianceShortName_;
      result.alliancePositions_ = alliancePositions_;
      result.player_ = player_;
      result.playerShortName_ = playerShortName_;
      result.playerIcon_ = playerIcon_;
      if (messageBuilder_ == null) {
        result.message_ = message_;
      } else {
        result.message_ = messageBuilder_.build();
      }
      result.sendTime_ = sendTime_;
      result.id_ = id_;
      result.playerId_ = playerId_;
      result.messageType_ = messageType_;
      result.office_ = office_;
      result.vipLv_ = vipLv_;
      result.areaNo_ = areaNo_;
      if (easyFightInfoBuilder_ == null) {
        result.easyFightInfo_ = easyFightInfo_;
      } else {
        result.easyFightInfo_ = easyFightInfoBuilder_.build();
      }
      if (massInfoBuilder_ == null) {
        result.massInfo_ = massInfo_;
      } else {
        result.massInfo_ = massInfoBuilder_.build();
      }
      result.chatRoomId_ = chatRoomId_;
      result.talkToId_ = talkToId_;
      result.x_ = x_;
      result.y_ = y_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pb4server.ChatInfoVo) {
        return mergeFrom((pb4server.ChatInfoVo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pb4server.ChatInfoVo other) {
      if (other == pb4server.ChatInfoVo.getDefaultInstance()) return this;
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (other.getIsSystem() != 0) {
        setIsSystem(other.getIsSystem());
      }
      if (other.getCountry() != 0) {
        setCountry(other.getCountry());
      }
      if (!other.getAllianceName().isEmpty()) {
        allianceName_ = other.allianceName_;
        onChanged();
      }
      if (!other.getAllianceShortName().isEmpty()) {
        allianceShortName_ = other.allianceShortName_;
        onChanged();
      }
      if (!other.getAlliancePositions().isEmpty()) {
        alliancePositions_ = other.alliancePositions_;
        onChanged();
      }
      if (!other.getPlayer().isEmpty()) {
        player_ = other.player_;
        onChanged();
      }
      if (!other.getPlayerShortName().isEmpty()) {
        playerShortName_ = other.playerShortName_;
        onChanged();
      }
      if (other.getPlayerIcon() != 0) {
        setPlayerIcon(other.getPlayerIcon());
      }
      if (other.hasMessage()) {
        mergeMessage(other.getMessage());
      }
      if (other.getSendTime() != 0) {
        setSendTime(other.getSendTime());
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getPlayerId() != 0L) {
        setPlayerId(other.getPlayerId());
      }
      if (other.getMessageType() != 0) {
        setMessageType(other.getMessageType());
      }
      if (other.getOffice() != 0) {
        setOffice(other.getOffice());
      }
      if (other.getVipLv() != 0) {
        setVipLv(other.getVipLv());
      }
      if (other.getAreaNo() != 0) {
        setAreaNo(other.getAreaNo());
      }
      if (other.hasEasyFightInfo()) {
        mergeEasyFightInfo(other.getEasyFightInfo());
      }
      if (other.hasMassInfo()) {
        mergeMassInfo(other.getMassInfo());
      }
      if (other.getChatRoomId() != 0L) {
        setChatRoomId(other.getChatRoomId());
      }
      if (other.getTalkToId() != 0L) {
        setTalkToId(other.getTalkToId());
      }
      if (other.getX() != 0) {
        setX(other.getX());
      }
      if (other.getY() != 0) {
        setY(other.getY());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pb4server.ChatInfoVo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pb4server.ChatInfoVo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ ;
    /**
     * <pre>
     *  聊天频道   0世界 1国家 2联盟 3跟好友聊天  4群聊
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     *  聊天频道   0世界 1国家 2联盟 3跟好友聊天  4群聊
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  聊天频道   0世界 1国家 2联盟 3跟好友聊天  4群聊
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int isSystem_ ;
    /**
     * <pre>
     * 是否是系统发布:0-玩家发布  1-系统发布
     * </pre>
     *
     * <code>int32 isSystem = 2;</code>
     */
    public int getIsSystem() {
      return isSystem_;
    }
    /**
     * <pre>
     * 是否是系统发布:0-玩家发布  1-系统发布
     * </pre>
     *
     * <code>int32 isSystem = 2;</code>
     */
    public Builder setIsSystem(int value) {
      
      isSystem_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否是系统发布:0-玩家发布  1-系统发布
     * </pre>
     *
     * <code>int32 isSystem = 2;</code>
     */
    public Builder clearIsSystem() {
      
      isSystem_ = 0;
      onChanged();
      return this;
    }

    private int country_ ;
    /**
     * <pre>
     * 真实国家
     * </pre>
     *
     * <code>int32 country = 3;</code>
     */
    public int getCountry() {
      return country_;
    }
    /**
     * <pre>
     * 真实国家
     * </pre>
     *
     * <code>int32 country = 3;</code>
     */
    public Builder setCountry(int value) {
      
      country_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 真实国家
     * </pre>
     *
     * <code>int32 country = 3;</code>
     */
    public Builder clearCountry() {
      
      country_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object allianceName_ = "";
    /**
     * <pre>
     * 联盟名称
     * </pre>
     *
     * <code>string allianceName = 4;</code>
     */
    public java.lang.String getAllianceName() {
      java.lang.Object ref = allianceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        allianceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 联盟名称
     * </pre>
     *
     * <code>string allianceName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAllianceNameBytes() {
      java.lang.Object ref = allianceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        allianceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 联盟名称
     * </pre>
     *
     * <code>string allianceName = 4;</code>
     */
    public Builder setAllianceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      allianceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 联盟名称
     * </pre>
     *
     * <code>string allianceName = 4;</code>
     */
    public Builder clearAllianceName() {
      
      allianceName_ = getDefaultInstance().getAllianceName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 联盟名称
     * </pre>
     *
     * <code>string allianceName = 4;</code>
     */
    public Builder setAllianceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      allianceName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object allianceShortName_ = "";
    /**
     * <pre>
     * 联盟简称
     * </pre>
     *
     * <code>string allianceShortName = 5;</code>
     */
    public java.lang.String getAllianceShortName() {
      java.lang.Object ref = allianceShortName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        allianceShortName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 联盟简称
     * </pre>
     *
     * <code>string allianceShortName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAllianceShortNameBytes() {
      java.lang.Object ref = allianceShortName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        allianceShortName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 联盟简称
     * </pre>
     *
     * <code>string allianceShortName = 5;</code>
     */
    public Builder setAllianceShortName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      allianceShortName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 联盟简称
     * </pre>
     *
     * <code>string allianceShortName = 5;</code>
     */
    public Builder clearAllianceShortName() {
      
      allianceShortName_ = getDefaultInstance().getAllianceShortName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 联盟简称
     * </pre>
     *
     * <code>string allianceShortName = 5;</code>
     */
    public Builder setAllianceShortNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      allianceShortName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object alliancePositions_ = "";
    /**
     * <pre>
     * 所属联盟官位
     * </pre>
     *
     * <code>string alliancePositions = 6;</code>
     */
    public java.lang.String getAlliancePositions() {
      java.lang.Object ref = alliancePositions_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alliancePositions_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 所属联盟官位
     * </pre>
     *
     * <code>string alliancePositions = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAlliancePositionsBytes() {
      java.lang.Object ref = alliancePositions_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alliancePositions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 所属联盟官位
     * </pre>
     *
     * <code>string alliancePositions = 6;</code>
     */
    public Builder setAlliancePositions(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      alliancePositions_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 所属联盟官位
     * </pre>
     *
     * <code>string alliancePositions = 6;</code>
     */
    public Builder clearAlliancePositions() {
      
      alliancePositions_ = getDefaultInstance().getAlliancePositions();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 所属联盟官位
     * </pre>
     *
     * <code>string alliancePositions = 6;</code>
     */
    public Builder setAlliancePositionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      alliancePositions_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object player_ = "";
    /**
     * <pre>
     * 说话者名字
     * </pre>
     *
     * <code>string player = 7;</code>
     */
    public java.lang.String getPlayer() {
      java.lang.Object ref = player_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        player_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 说话者名字
     * </pre>
     *
     * <code>string player = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerBytes() {
      java.lang.Object ref = player_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        player_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 说话者名字
     * </pre>
     *
     * <code>string player = 7;</code>
     */
    public Builder setPlayer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      player_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 说话者名字
     * </pre>
     *
     * <code>string player = 7;</code>
     */
    public Builder clearPlayer() {
      
      player_ = getDefaultInstance().getPlayer();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 说话者名字
     * </pre>
     *
     * <code>string player = 7;</code>
     */
    public Builder setPlayerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      player_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object playerShortName_ = "";
    /**
     * <pre>
     * 玩家昵称
     * </pre>
     *
     * <code>string playerShortName = 8;</code>
     */
    public java.lang.String getPlayerShortName() {
      java.lang.Object ref = playerShortName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerShortName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 玩家昵称
     * </pre>
     *
     * <code>string playerShortName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerShortNameBytes() {
      java.lang.Object ref = playerShortName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerShortName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 玩家昵称
     * </pre>
     *
     * <code>string playerShortName = 8;</code>
     */
    public Builder setPlayerShortName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      playerShortName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 玩家昵称
     * </pre>
     *
     * <code>string playerShortName = 8;</code>
     */
    public Builder clearPlayerShortName() {
      
      playerShortName_ = getDefaultInstance().getPlayerShortName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 玩家昵称
     * </pre>
     *
     * <code>string playerShortName = 8;</code>
     */
    public Builder setPlayerShortNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      playerShortName_ = value;
      onChanged();
      return this;
    }

    private int playerIcon_ ;
    /**
     * <pre>
     * 头像模板id
     * </pre>
     *
     * <code>int32 playerIcon = 9;</code>
     */
    public int getPlayerIcon() {
      return playerIcon_;
    }
    /**
     * <pre>
     * 头像模板id
     * </pre>
     *
     * <code>int32 playerIcon = 9;</code>
     */
    public Builder setPlayerIcon(int value) {
      
      playerIcon_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 头像模板id
     * </pre>
     *
     * <code>int32 playerIcon = 9;</code>
     */
    public Builder clearPlayerIcon() {
      
      playerIcon_ = 0;
      onChanged();
      return this;
    }

    private pb4server.NoticeVo message_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        pb4server.NoticeVo, pb4server.NoticeVo.Builder, pb4server.NoticeVoOrBuilder> messageBuilder_;
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>.pb4server.NoticeVo message = 10;</code>
     */
    public boolean hasMessage() {
      return messageBuilder_ != null || message_ != null;
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>.pb4server.NoticeVo message = 10;</code>
     */
    public pb4server.NoticeVo getMessage() {
      if (messageBuilder_ == null) {
        return message_ == null ? pb4server.NoticeVo.getDefaultInstance() : message_;
      } else {
        return messageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>.pb4server.NoticeVo message = 10;</code>
     */
    public Builder setMessage(pb4server.NoticeVo value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        messageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>.pb4server.NoticeVo message = 10;</code>
     */
    public Builder setMessage(
        pb4server.NoticeVo.Builder builderForValue) {
      if (messageBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>.pb4server.NoticeVo message = 10;</code>
     */
    public Builder mergeMessage(pb4server.NoticeVo value) {
      if (messageBuilder_ == null) {
        if (message_ != null) {
          message_ =
            pb4server.NoticeVo.newBuilder(message_).mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        messageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>.pb4server.NoticeVo message = 10;</code>
     */
    public Builder clearMessage() {
      if (messageBuilder_ == null) {
        message_ = null;
        onChanged();
      } else {
        message_ = null;
        messageBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>.pb4server.NoticeVo message = 10;</code>
     */
    public pb4server.NoticeVo.Builder getMessageBuilder() {
      
      onChanged();
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>.pb4server.NoticeVo message = 10;</code>
     */
    public pb4server.NoticeVoOrBuilder getMessageOrBuilder() {
      if (messageBuilder_ != null) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        return message_ == null ?
            pb4server.NoticeVo.getDefaultInstance() : message_;
      }
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>.pb4server.NoticeVo message = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pb4server.NoticeVo, pb4server.NoticeVo.Builder, pb4server.NoticeVoOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pb4server.NoticeVo, pb4server.NoticeVo.Builder, pb4server.NoticeVoOrBuilder>(
                getMessage(),
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      return messageBuilder_;
    }

    private int sendTime_ ;
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>int32 sendTime = 11;</code>
     */
    public int getSendTime() {
      return sendTime_;
    }
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>int32 sendTime = 11;</code>
     */
    public Builder setSendTime(int value) {
      
      sendTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>int32 sendTime = 11;</code>
     */
    public Builder clearSendTime() {
      
      sendTime_ = 0;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <pre>
     * 唯一ID
     * </pre>
     *
     * <code>int64 id = 12;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * 唯一ID
     * </pre>
     *
     * <code>int64 id = 12;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 唯一ID
     * </pre>
     *
     * <code>int64 id = 12;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private long playerId_ ;
    /**
     * <pre>
     * 玩家ID
     * </pre>
     *
     * <code>int64 playerId = 13;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }
    /**
     * <pre>
     * 玩家ID
     * </pre>
     *
     * <code>int64 playerId = 13;</code>
     */
    public Builder setPlayerId(long value) {
      
      playerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 玩家ID
     * </pre>
     *
     * <code>int64 playerId = 13;</code>
     */
    public Builder clearPlayerId() {
      
      playerId_ = 0L;
      onChanged();
      return this;
    }

    private int messageType_ ;
    /**
     * <pre>
     * 消息类型  1-普通消息  2-红包消息（暂时被砍） 3-表情  4-战报分享  5-集结  6-喇叭 7-坐标
     * </pre>
     *
     * <code>int32 messageType = 14;</code>
     */
    public int getMessageType() {
      return messageType_;
    }
    /**
     * <pre>
     * 消息类型  1-普通消息  2-红包消息（暂时被砍） 3-表情  4-战报分享  5-集结  6-喇叭 7-坐标
     * </pre>
     *
     * <code>int32 messageType = 14;</code>
     */
    public Builder setMessageType(int value) {
      
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型  1-普通消息  2-红包消息（暂时被砍） 3-表情  4-战报分享  5-集结  6-喇叭 7-坐标
     * </pre>
     *
     * <code>int32 messageType = 14;</code>
     */
    public Builder clearMessageType() {
      
      messageType_ = 0;
      onChanged();
      return this;
    }

    private int office_ ;
    /**
     * <pre>
     *官职Id
     * </pre>
     *
     * <code>int32 office = 15;</code>
     */
    public int getOffice() {
      return office_;
    }
    /**
     * <pre>
     *官职Id
     * </pre>
     *
     * <code>int32 office = 15;</code>
     */
    public Builder setOffice(int value) {
      
      office_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *官职Id
     * </pre>
     *
     * <code>int32 office = 15;</code>
     */
    public Builder clearOffice() {
      
      office_ = 0;
      onChanged();
      return this;
    }

    private int vipLv_ ;
    /**
     * <pre>
     * vip等级
     * </pre>
     *
     * <code>int32 vipLv = 16;</code>
     */
    public int getVipLv() {
      return vipLv_;
    }
    /**
     * <pre>
     * vip等级
     * </pre>
     *
     * <code>int32 vipLv = 16;</code>
     */
    public Builder setVipLv(int value) {
      
      vipLv_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * vip等级
     * </pre>
     *
     * <code>int32 vipLv = 16;</code>
     */
    public Builder clearVipLv() {
      
      vipLv_ = 0;
      onChanged();
      return this;
    }

    private int areaNo_ ;
    /**
     * <pre>
     * 服务器编号
     * </pre>
     *
     * <code>int32 areaNo = 17;</code>
     */
    public int getAreaNo() {
      return areaNo_;
    }
    /**
     * <pre>
     * 服务器编号
     * </pre>
     *
     * <code>int32 areaNo = 17;</code>
     */
    public Builder setAreaNo(int value) {
      
      areaNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 服务器编号
     * </pre>
     *
     * <code>int32 areaNo = 17;</code>
     */
    public Builder clearAreaNo() {
      
      areaNo_ = 0;
      onChanged();
      return this;
    }

    private pb4server.SimpleFightReportVo easyFightInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        pb4server.SimpleFightReportVo, pb4server.SimpleFightReportVo.Builder, pb4server.SimpleFightReportVoOrBuilder> easyFightInfoBuilder_;
    /**
     * <pre>
     * 战报分享
     * </pre>
     *
     * <code>.pb4server.SimpleFightReportVo easyFightInfo = 18;</code>
     */
    public boolean hasEasyFightInfo() {
      return easyFightInfoBuilder_ != null || easyFightInfo_ != null;
    }
    /**
     * <pre>
     * 战报分享
     * </pre>
     *
     * <code>.pb4server.SimpleFightReportVo easyFightInfo = 18;</code>
     */
    public pb4server.SimpleFightReportVo getEasyFightInfo() {
      if (easyFightInfoBuilder_ == null) {
        return easyFightInfo_ == null ? pb4server.SimpleFightReportVo.getDefaultInstance() : easyFightInfo_;
      } else {
        return easyFightInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 战报分享
     * </pre>
     *
     * <code>.pb4server.SimpleFightReportVo easyFightInfo = 18;</code>
     */
    public Builder setEasyFightInfo(pb4server.SimpleFightReportVo value) {
      if (easyFightInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        easyFightInfo_ = value;
        onChanged();
      } else {
        easyFightInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 战报分享
     * </pre>
     *
     * <code>.pb4server.SimpleFightReportVo easyFightInfo = 18;</code>
     */
    public Builder setEasyFightInfo(
        pb4server.SimpleFightReportVo.Builder builderForValue) {
      if (easyFightInfoBuilder_ == null) {
        easyFightInfo_ = builderForValue.build();
        onChanged();
      } else {
        easyFightInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 战报分享
     * </pre>
     *
     * <code>.pb4server.SimpleFightReportVo easyFightInfo = 18;</code>
     */
    public Builder mergeEasyFightInfo(pb4server.SimpleFightReportVo value) {
      if (easyFightInfoBuilder_ == null) {
        if (easyFightInfo_ != null) {
          easyFightInfo_ =
            pb4server.SimpleFightReportVo.newBuilder(easyFightInfo_).mergeFrom(value).buildPartial();
        } else {
          easyFightInfo_ = value;
        }
        onChanged();
      } else {
        easyFightInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 战报分享
     * </pre>
     *
     * <code>.pb4server.SimpleFightReportVo easyFightInfo = 18;</code>
     */
    public Builder clearEasyFightInfo() {
      if (easyFightInfoBuilder_ == null) {
        easyFightInfo_ = null;
        onChanged();
      } else {
        easyFightInfo_ = null;
        easyFightInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 战报分享
     * </pre>
     *
     * <code>.pb4server.SimpleFightReportVo easyFightInfo = 18;</code>
     */
    public pb4server.SimpleFightReportVo.Builder getEasyFightInfoBuilder() {
      
      onChanged();
      return getEasyFightInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 战报分享
     * </pre>
     *
     * <code>.pb4server.SimpleFightReportVo easyFightInfo = 18;</code>
     */
    public pb4server.SimpleFightReportVoOrBuilder getEasyFightInfoOrBuilder() {
      if (easyFightInfoBuilder_ != null) {
        return easyFightInfoBuilder_.getMessageOrBuilder();
      } else {
        return easyFightInfo_ == null ?
            pb4server.SimpleFightReportVo.getDefaultInstance() : easyFightInfo_;
      }
    }
    /**
     * <pre>
     * 战报分享
     * </pre>
     *
     * <code>.pb4server.SimpleFightReportVo easyFightInfo = 18;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pb4server.SimpleFightReportVo, pb4server.SimpleFightReportVo.Builder, pb4server.SimpleFightReportVoOrBuilder> 
        getEasyFightInfoFieldBuilder() {
      if (easyFightInfoBuilder_ == null) {
        easyFightInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pb4server.SimpleFightReportVo, pb4server.SimpleFightReportVo.Builder, pb4server.SimpleFightReportVoOrBuilder>(
                getEasyFightInfo(),
                getParentForChildren(),
                isClean());
        easyFightInfo_ = null;
      }
      return easyFightInfoBuilder_;
    }

    private pb4server.SimpleMassInfoVo massInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        pb4server.SimpleMassInfoVo, pb4server.SimpleMassInfoVo.Builder, pb4server.SimpleMassInfoVoOrBuilder> massInfoBuilder_;
    /**
     * <pre>
     * 集结信息
     * </pre>
     *
     * <code>.pb4server.SimpleMassInfoVo massInfo = 19;</code>
     */
    public boolean hasMassInfo() {
      return massInfoBuilder_ != null || massInfo_ != null;
    }
    /**
     * <pre>
     * 集结信息
     * </pre>
     *
     * <code>.pb4server.SimpleMassInfoVo massInfo = 19;</code>
     */
    public pb4server.SimpleMassInfoVo getMassInfo() {
      if (massInfoBuilder_ == null) {
        return massInfo_ == null ? pb4server.SimpleMassInfoVo.getDefaultInstance() : massInfo_;
      } else {
        return massInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 集结信息
     * </pre>
     *
     * <code>.pb4server.SimpleMassInfoVo massInfo = 19;</code>
     */
    public Builder setMassInfo(pb4server.SimpleMassInfoVo value) {
      if (massInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        massInfo_ = value;
        onChanged();
      } else {
        massInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 集结信息
     * </pre>
     *
     * <code>.pb4server.SimpleMassInfoVo massInfo = 19;</code>
     */
    public Builder setMassInfo(
        pb4server.SimpleMassInfoVo.Builder builderForValue) {
      if (massInfoBuilder_ == null) {
        massInfo_ = builderForValue.build();
        onChanged();
      } else {
        massInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 集结信息
     * </pre>
     *
     * <code>.pb4server.SimpleMassInfoVo massInfo = 19;</code>
     */
    public Builder mergeMassInfo(pb4server.SimpleMassInfoVo value) {
      if (massInfoBuilder_ == null) {
        if (massInfo_ != null) {
          massInfo_ =
            pb4server.SimpleMassInfoVo.newBuilder(massInfo_).mergeFrom(value).buildPartial();
        } else {
          massInfo_ = value;
        }
        onChanged();
      } else {
        massInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 集结信息
     * </pre>
     *
     * <code>.pb4server.SimpleMassInfoVo massInfo = 19;</code>
     */
    public Builder clearMassInfo() {
      if (massInfoBuilder_ == null) {
        massInfo_ = null;
        onChanged();
      } else {
        massInfo_ = null;
        massInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 集结信息
     * </pre>
     *
     * <code>.pb4server.SimpleMassInfoVo massInfo = 19;</code>
     */
    public pb4server.SimpleMassInfoVo.Builder getMassInfoBuilder() {
      
      onChanged();
      return getMassInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 集结信息
     * </pre>
     *
     * <code>.pb4server.SimpleMassInfoVo massInfo = 19;</code>
     */
    public pb4server.SimpleMassInfoVoOrBuilder getMassInfoOrBuilder() {
      if (massInfoBuilder_ != null) {
        return massInfoBuilder_.getMessageOrBuilder();
      } else {
        return massInfo_ == null ?
            pb4server.SimpleMassInfoVo.getDefaultInstance() : massInfo_;
      }
    }
    /**
     * <pre>
     * 集结信息
     * </pre>
     *
     * <code>.pb4server.SimpleMassInfoVo massInfo = 19;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pb4server.SimpleMassInfoVo, pb4server.SimpleMassInfoVo.Builder, pb4server.SimpleMassInfoVoOrBuilder> 
        getMassInfoFieldBuilder() {
      if (massInfoBuilder_ == null) {
        massInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pb4server.SimpleMassInfoVo, pb4server.SimpleMassInfoVo.Builder, pb4server.SimpleMassInfoVoOrBuilder>(
                getMassInfo(),
                getParentForChildren(),
                isClean());
        massInfo_ = null;
      }
      return massInfoBuilder_;
    }

    private long chatRoomId_ ;
    /**
     * <pre>
     * 聊天室Id
     * </pre>
     *
     * <code>int64 chatRoomId = 20;</code>
     */
    public long getChatRoomId() {
      return chatRoomId_;
    }
    /**
     * <pre>
     * 聊天室Id
     * </pre>
     *
     * <code>int64 chatRoomId = 20;</code>
     */
    public Builder setChatRoomId(long value) {
      
      chatRoomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 聊天室Id
     * </pre>
     *
     * <code>int64 chatRoomId = 20;</code>
     */
    public Builder clearChatRoomId() {
      
      chatRoomId_ = 0L;
      onChanged();
      return this;
    }

    private long talkToId_ ;
    /**
     * <pre>
     * 我的聊天对象id
     * </pre>
     *
     * <code>int64 talkToId = 21;</code>
     */
    public long getTalkToId() {
      return talkToId_;
    }
    /**
     * <pre>
     * 我的聊天对象id
     * </pre>
     *
     * <code>int64 talkToId = 21;</code>
     */
    public Builder setTalkToId(long value) {
      
      talkToId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 我的聊天对象id
     * </pre>
     *
     * <code>int64 talkToId = 21;</code>
     */
    public Builder clearTalkToId() {
      
      talkToId_ = 0L;
      onChanged();
      return this;
    }

    private int x_ ;
    /**
     * <pre>
     * 坐标x
     * </pre>
     *
     * <code>int32 x = 22;</code>
     */
    public int getX() {
      return x_;
    }
    /**
     * <pre>
     * 坐标x
     * </pre>
     *
     * <code>int32 x = 22;</code>
     */
    public Builder setX(int value) {
      
      x_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 坐标x
     * </pre>
     *
     * <code>int32 x = 22;</code>
     */
    public Builder clearX() {
      
      x_ = 0;
      onChanged();
      return this;
    }

    private int y_ ;
    /**
     * <pre>
     * 坐标y
     * </pre>
     *
     * <code>int32 y = 23;</code>
     */
    public int getY() {
      return y_;
    }
    /**
     * <pre>
     * 坐标y
     * </pre>
     *
     * <code>int32 y = 23;</code>
     */
    public Builder setY(int value) {
      
      y_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 坐标y
     * </pre>
     *
     * <code>int32 y = 23;</code>
     */
    public Builder clearY() {
      
      y_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:pb4server.ChatInfoVo)
  }

  // @@protoc_insertion_point(class_scope:pb4server.ChatInfoVo)
  private static final pb4server.ChatInfoVo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pb4server.ChatInfoVo();
  }

  public static pb4server.ChatInfoVo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatInfoVo>
      PARSER = new com.google.protobuf.AbstractParser<ChatInfoVo>() {
    public ChatInfoVo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatInfoVo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChatInfoVo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatInfoVo> getParserForType() {
    return PARSER;
  }

  public pb4server.ChatInfoVo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

