// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal2public.proto

package pb4server;

public interface DealJoinAllianceAskRtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb4server.DealJoinAllianceAskRt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rt = 1;</code>
   */
  int getRt();
}
