// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal2public.proto

package pb4server;

public interface Home2PublicAskRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb4server.Home2PublicAskResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 playerId = 1;</code>
   */
  long getPlayerId();

  /**
   * <code>int32 clientMsgNo = 2;</code>
   */
  int getClientMsgNo();

  /**
   * <code>.pb4server.SetAllianceFlagAskRt setAllianceFlagAskRt = 11;</code>
   */
  pb4server.SetAllianceFlagAskRt getSetAllianceFlagAskRt();
  /**
   * <code>.pb4server.SetAllianceFlagAskRt setAllianceFlagAskRt = 11;</code>
   */
  pb4server.SetAllianceFlagAskRtOrBuilder getSetAllianceFlagAskRtOrBuilder();

  /**
   * <code>.pb4server.RemoveAllianceHelpAskRt removeAllianceHelpAskRt = 12;</code>
   */
  pb4server.RemoveAllianceHelpAskRt getRemoveAllianceHelpAskRt();
  /**
   * <code>.pb4server.RemoveAllianceHelpAskRt removeAllianceHelpAskRt = 12;</code>
   */
  pb4server.RemoveAllianceHelpAskRtOrBuilder getRemoveAllianceHelpAskRtOrBuilder();

  /**
   * <code>.pb4server.AllianceImpeachAskRt allianceImpeachAskRt = 13;</code>
   */
  pb4server.AllianceImpeachAskRt getAllianceImpeachAskRt();
  /**
   * <code>.pb4server.AllianceImpeachAskRt allianceImpeachAskRt = 13;</code>
   */
  pb4server.AllianceImpeachAskRtOrBuilder getAllianceImpeachAskRtOrBuilder();

  /**
   * <code>.pb4server.AllianceMemberQuitAskRt allianceMemberQuitAskRt = 14;</code>
   */
  pb4server.AllianceMemberQuitAskRt getAllianceMemberQuitAskRt();
  /**
   * <code>.pb4server.AllianceMemberQuitAskRt allianceMemberQuitAskRt = 14;</code>
   */
  pb4server.AllianceMemberQuitAskRtOrBuilder getAllianceMemberQuitAskRtOrBuilder();

  /**
   * <code>.pb4server.SetAllianceNameAskRt setAllianceNameAskRt = 15;</code>
   */
  pb4server.SetAllianceNameAskRt getSetAllianceNameAskRt();
  /**
   * <code>.pb4server.SetAllianceNameAskRt setAllianceNameAskRt = 15;</code>
   */
  pb4server.SetAllianceNameAskRtOrBuilder getSetAllianceNameAskRtOrBuilder();

  /**
   * <code>.pb4server.SendAllianceHelpAskRt sendAllianceHelpAskRt = 16;</code>
   */
  pb4server.SendAllianceHelpAskRt getSendAllianceHelpAskRt();
  /**
   * <code>.pb4server.SendAllianceHelpAskRt sendAllianceHelpAskRt = 16;</code>
   */
  pb4server.SendAllianceHelpAskRtOrBuilder getSendAllianceHelpAskRtOrBuilder();

  /**
   * <code>.pb4server.GoAllianceHelpAskRt goAllianceHelpAskRt = 17;</code>
   */
  pb4server.GoAllianceHelpAskRt getGoAllianceHelpAskRt();
  /**
   * <code>.pb4server.GoAllianceHelpAskRt goAllianceHelpAskRt = 17;</code>
   */
  pb4server.GoAllianceHelpAskRtOrBuilder getGoAllianceHelpAskRtOrBuilder();

  /**
   * <code>.pb4server.OpenAllianceHelpAskRt openAllianceHelpAskRt = 18;</code>
   */
  pb4server.OpenAllianceHelpAskRt getOpenAllianceHelpAskRt();
  /**
   * <code>.pb4server.OpenAllianceHelpAskRt openAllianceHelpAskRt = 18;</code>
   */
  pb4server.OpenAllianceHelpAskRtOrBuilder getOpenAllianceHelpAskRtOrBuilder();

  /**
   * <code>.pb4server.OpenAllianceCompetitionMainAskRt openAllianceCompetitionMainAskRt = 19;</code>
   */
  pb4server.OpenAllianceCompetitionMainAskRt getOpenAllianceCompetitionMainAskRt();
  /**
   * <code>.pb4server.OpenAllianceCompetitionMainAskRt openAllianceCompetitionMainAskRt = 19;</code>
   */
  pb4server.OpenAllianceCompetitionMainAskRtOrBuilder getOpenAllianceCompetitionMainAskRtOrBuilder();

  /**
   * <code>.pb4server.GetAllianceCompetitionQuestAskRt getAllianceCompetitionQuestAskRt = 20;</code>
   */
  pb4server.GetAllianceCompetitionQuestAskRt getGetAllianceCompetitionQuestAskRt();
  /**
   * <code>.pb4server.GetAllianceCompetitionQuestAskRt getAllianceCompetitionQuestAskRt = 20;</code>
   */
  pb4server.GetAllianceCompetitionQuestAskRtOrBuilder getGetAllianceCompetitionQuestAskRtOrBuilder();

  /**
   * <code>.pb4server.RewardAllianceCompetitionQuestAskRt rewardAllianceCompetitionQuestAskRt = 21;</code>
   */
  pb4server.RewardAllianceCompetitionQuestAskRt getRewardAllianceCompetitionQuestAskRt();
  /**
   * <code>.pb4server.RewardAllianceCompetitionQuestAskRt rewardAllianceCompetitionQuestAskRt = 21;</code>
   */
  pb4server.RewardAllianceCompetitionQuestAskRtOrBuilder getRewardAllianceCompetitionQuestAskRtOrBuilder();

  /**
   * <code>.pb4server.CancelAllianceCompetitionQuestAskRt cancelAllianceCompetitionQuestAskRt = 22;</code>
   */
  pb4server.CancelAllianceCompetitionQuestAskRt getCancelAllianceCompetitionQuestAskRt();
  /**
   * <code>.pb4server.CancelAllianceCompetitionQuestAskRt cancelAllianceCompetitionQuestAskRt = 22;</code>
   */
  pb4server.CancelAllianceCompetitionQuestAskRtOrBuilder getCancelAllianceCompetitionQuestAskRtOrBuilder();

  /**
   * <code>.pb4server.GetAllianceCompetitionRewardAskRt getAllianceCompetitionRewardAskRt = 23;</code>
   */
  pb4server.GetAllianceCompetitionRewardAskRt getGetAllianceCompetitionRewardAskRt();
  /**
   * <code>.pb4server.GetAllianceCompetitionRewardAskRt getAllianceCompetitionRewardAskRt = 23;</code>
   */
  pb4server.GetAllianceCompetitionRewardAskRtOrBuilder getGetAllianceCompetitionRewardAskRtOrBuilder();

  /**
   * <code>.pb4server.GetCasinoAskRt getCasinoAskRt = 25;</code>
   */
  pb4server.GetCasinoAskRt getGetCasinoAskRt();
  /**
   * <code>.pb4server.GetCasinoAskRt getCasinoAskRt = 25;</code>
   */
  pb4server.GetCasinoAskRtOrBuilder getGetCasinoAskRtOrBuilder();

  /**
   * <code>.pb4server.DrawCasinoAskRt drawCasinoAskRt = 26;</code>
   */
  pb4server.DrawCasinoAskRt getDrawCasinoAskRt();
  /**
   * <code>.pb4server.DrawCasinoAskRt drawCasinoAskRt = 26;</code>
   */
  pb4server.DrawCasinoAskRtOrBuilder getDrawCasinoAskRtOrBuilder();

  /**
   * <code>.pb4server.UpdateAllianceMemberInfoInHomeAskRt updateAllianceMemberInfoInHomeAskRt = 27;</code>
   */
  pb4server.UpdateAllianceMemberInfoInHomeAskRt getUpdateAllianceMemberInfoInHomeAskRt();
  /**
   * <code>.pb4server.UpdateAllianceMemberInfoInHomeAskRt updateAllianceMemberInfoInHomeAskRt = 27;</code>
   */
  pb4server.UpdateAllianceMemberInfoInHomeAskRtOrBuilder getUpdateAllianceMemberInfoInHomeAskRtOrBuilder();

  /**
   * <code>.pb4server.RoomOwnerChangeAskRt roomOwnerChangeAskRt = 28;</code>
   */
  pb4server.RoomOwnerChangeAskRt getRoomOwnerChangeAskRt();
  /**
   * <code>.pb4server.RoomOwnerChangeAskRt roomOwnerChangeAskRt = 28;</code>
   */
  pb4server.RoomOwnerChangeAskRtOrBuilder getRoomOwnerChangeAskRtOrBuilder();

  /**
   * <code>.pb4server.CreateRoomAskRt createRoomAskRt = 29;</code>
   */
  pb4server.CreateRoomAskRt getCreateRoomAskRt();
  /**
   * <code>.pb4server.CreateRoomAskRt createRoomAskRt = 29;</code>
   */
  pb4server.CreateRoomAskRtOrBuilder getCreateRoomAskRtOrBuilder();

  /**
   * <code>.pb4server.DissmissChatRoomAskRt dissmissChatRoomAskRt = 30;</code>
   */
  pb4server.DissmissChatRoomAskRt getDissmissChatRoomAskRt();
  /**
   * <code>.pb4server.DissmissChatRoomAskRt dissmissChatRoomAskRt = 30;</code>
   */
  pb4server.DissmissChatRoomAskRtOrBuilder getDissmissChatRoomAskRtOrBuilder();

  /**
   * <code>.pb4server.GetAllianceChatAskRt getAllianceChatAskRt = 31;</code>
   */
  pb4server.GetAllianceChatAskRt getGetAllianceChatAskRt();
  /**
   * <code>.pb4server.GetAllianceChatAskRt getAllianceChatAskRt = 31;</code>
   */
  pb4server.GetAllianceChatAskRtOrBuilder getGetAllianceChatAskRtOrBuilder();

  /**
   * <code>.pb4server.InviteJoinChatAskRt inviteJoinChatAskRt = 32;</code>
   */
  pb4server.InviteJoinChatAskRt getInviteJoinChatAskRt();
  /**
   * <code>.pb4server.InviteJoinChatAskRt inviteJoinChatAskRt = 32;</code>
   */
  pb4server.InviteJoinChatAskRtOrBuilder getInviteJoinChatAskRtOrBuilder();

  /**
   * <code>.pb4server.KickOutChatRoomAskRt kickOutChatRoomAskRt = 33;</code>
   */
  pb4server.KickOutChatRoomAskRt getKickOutChatRoomAskRt();
  /**
   * <code>.pb4server.KickOutChatRoomAskRt kickOutChatRoomAskRt = 33;</code>
   */
  pb4server.KickOutChatRoomAskRtOrBuilder getKickOutChatRoomAskRtOrBuilder();

  /**
   * <code>.pb4server.QueryMemberInRoomAskRt queryMemberInRoomAskRt = 34;</code>
   */
  pb4server.QueryMemberInRoomAskRt getQueryMemberInRoomAskRt();
  /**
   * <code>.pb4server.QueryMemberInRoomAskRt queryMemberInRoomAskRt = 34;</code>
   */
  pb4server.QueryMemberInRoomAskRtOrBuilder getQueryMemberInRoomAskRtOrBuilder();

  /**
   * <code>.pb4server.QuitOneRoomAskRt quitOneRoomAskRt = 35;</code>
   */
  pb4server.QuitOneRoomAskRt getQuitOneRoomAskRt();
  /**
   * <code>.pb4server.QuitOneRoomAskRt quitOneRoomAskRt = 35;</code>
   */
  pb4server.QuitOneRoomAskRtOrBuilder getQuitOneRoomAskRtOrBuilder();

  /**
   * <code>.pb4server.RenameChatRoomAskRt renameChatRoomAskRt = 36;</code>
   */
  pb4server.RenameChatRoomAskRt getRenameChatRoomAskRt();
  /**
   * <code>.pb4server.RenameChatRoomAskRt renameChatRoomAskRt = 36;</code>
   */
  pb4server.RenameChatRoomAskRtOrBuilder getRenameChatRoomAskRtOrBuilder();

  /**
   * <code>.pb4server.SendAllianceChatAskRt sendAllianceChatAskRt = 37;</code>
   */
  pb4server.SendAllianceChatAskRt getSendAllianceChatAskRt();
  /**
   * <code>.pb4server.SendAllianceChatAskRt sendAllianceChatAskRt = 37;</code>
   */
  pb4server.SendAllianceChatAskRtOrBuilder getSendAllianceChatAskRtOrBuilder();

  /**
   * <code>.pb4server.SendRoomMsgAskRt sendRoomMsgAskRt = 38;</code>
   */
  pb4server.SendRoomMsgAskRt getSendRoomMsgAskRt();
  /**
   * <code>.pb4server.SendRoomMsgAskRt sendRoomMsgAskRt = 38;</code>
   */
  pb4server.SendRoomMsgAskRtOrBuilder getSendRoomMsgAskRtOrBuilder();

  /**
   * <code>.pb4server.GetGroupChatAskRt getGroupChatAskRt = 39;</code>
   */
  pb4server.GetGroupChatAskRt getGetGroupChatAskRt();
  /**
   * <code>.pb4server.GetGroupChatAskRt getGroupChatAskRt = 39;</code>
   */
  pb4server.GetGroupChatAskRtOrBuilder getGetGroupChatAskRtOrBuilder();

  /**
   * <code>.pb4server.GetChatroomAskRt getChatroomAskRt = 40;</code>
   */
  pb4server.GetChatroomAskRt getGetChatroomAskRt();
  /**
   * <code>.pb4server.GetChatroomAskRt getChatroomAskRt = 40;</code>
   */
  pb4server.GetChatroomAskRtOrBuilder getGetChatroomAskRtOrBuilder();

  /**
   * <code>.pb4server.ReceiveAllianceGiftAskRt receiveAllianceGiftAskRt = 41;</code>
   */
  pb4server.ReceiveAllianceGiftAskRt getReceiveAllianceGiftAskRt();
  /**
   * <code>.pb4server.ReceiveAllianceGiftAskRt receiveAllianceGiftAskRt = 41;</code>
   */
  pb4server.ReceiveAllianceGiftAskRtOrBuilder getReceiveAllianceGiftAskRtOrBuilder();

  /**
   * <code>.pb4server.RemoveAllianceWaijiaoRt removeAllianceWaijiaoRt = 42;</code>
   */
  pb4server.RemoveAllianceWaijiaoRt getRemoveAllianceWaijiaoRt();
  /**
   * <code>.pb4server.RemoveAllianceWaijiaoRt removeAllianceWaijiaoRt = 42;</code>
   */
  pb4server.RemoveAllianceWaijiaoRtOrBuilder getRemoveAllianceWaijiaoRtOrBuilder();

  public pb4server.Home2PublicAskResp.MsgCase getMsgCase();
}
