// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal2public.proto

package pb4server;

public interface KickOutChatRoomAskReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb4server.KickOutChatRoomAskReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 roomId = 1;</code>
   */
  long getRoomId();

  /**
   * <code>int64 playerIdRemove = 2;</code>
   */
  long getPlayerIdRemove();
}
