// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internalpb2.proto

package pb4server;

public interface MulticastEnvelopeMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb4server.MulticastEnvelopeMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 msgType = 1;</code>
   */
  boolean hasMsgType();
  /**
   * <code>optional int32 msgType = 1;</code>
   */
  int getMsgType();

  /**
   * <code>optional .pb4server.SubscribeCmd subscribeCmd = 2;</code>
   */
  boolean hasSubscribeCmd();
  /**
   * <code>optional .pb4server.SubscribeCmd subscribeCmd = 2;</code>
   */
  pb4server.SubscribeCmd getSubscribeCmd();
  /**
   * <code>optional .pb4server.SubscribeCmd subscribeCmd = 2;</code>
   */
  pb4server.SubscribeCmdOrBuilder getSubscribeCmdOrBuilder();

  /**
   * <code>optional .pb4server.UnsubscribeCmd unsubscribeCmd = 3;</code>
   */
  boolean hasUnsubscribeCmd();
  /**
   * <code>optional .pb4server.UnsubscribeCmd unsubscribeCmd = 3;</code>
   */
  pb4server.UnsubscribeCmd getUnsubscribeCmd();
  /**
   * <code>optional .pb4server.UnsubscribeCmd unsubscribeCmd = 3;</code>
   */
  pb4server.UnsubscribeCmdOrBuilder getUnsubscribeCmdOrBuilder();

  /**
   * <code>optional .client2server.NewChatMessage newChatMsg = 4;</code>
   */
  boolean hasNewChatMsg();
  /**
   * <code>optional .client2server.NewChatMessage newChatMsg = 4;</code>
   */
  pb4client.NewChatMessage getNewChatMsg();
  /**
   * <code>optional .client2server.NewChatMessage newChatMsg = 4;</code>
   */
  pb4client.NewChatMessageOrBuilder getNewChatMsgOrBuilder();

  /**
   * <code>optional .client2server.GroupChatInfo groupChatMsg = 5;</code>
   */
  boolean hasGroupChatMsg();
  /**
   * <code>optional .client2server.GroupChatInfo groupChatMsg = 5;</code>
   */
  pb4client.GroupChatInfo getGroupChatMsg();
  /**
   * <code>optional .client2server.GroupChatInfo groupChatMsg = 5;</code>
   */
  pb4client.GroupChatInfoOrBuilder getGroupChatMsgOrBuilder();

  /**
   * <code>optional .pb4server.AddMulticastBlackList addMulticastBlackList = 6;</code>
   */
  boolean hasAddMulticastBlackList();
  /**
   * <code>optional .pb4server.AddMulticastBlackList addMulticastBlackList = 6;</code>
   */
  pb4server.AddMulticastBlackList getAddMulticastBlackList();
  /**
   * <code>optional .pb4server.AddMulticastBlackList addMulticastBlackList = 6;</code>
   */
  pb4server.AddMulticastBlackListOrBuilder getAddMulticastBlackListOrBuilder();

  /**
   * <code>optional .pb4server.DelMulticastBlackList delMulticastBlackList = 7;</code>
   */
  boolean hasDelMulticastBlackList();
  /**
   * <code>optional .pb4server.DelMulticastBlackList delMulticastBlackList = 7;</code>
   */
  pb4server.DelMulticastBlackList getDelMulticastBlackList();
  /**
   * <code>optional .pb4server.DelMulticastBlackList delMulticastBlackList = 7;</code>
   */
  pb4server.DelMulticastBlackListOrBuilder getDelMulticastBlackListOrBuilder();

  /**
   * <code>optional string channel = 8;</code>
   */
  boolean hasChannel();
  /**
   * <code>optional string channel = 8;</code>
   */
  java.lang.String getChannel();
  /**
   * <code>optional string channel = 8;</code>
   */
  com.google.protobuf.ByteString
      getChannelBytes();

  /**
   * <code>repeated int64 excludePlayerIds = 9;</code>
   */
  java.util.List<java.lang.Long> getExcludePlayerIdsList();
  /**
   * <code>repeated int64 excludePlayerIds = 9;</code>
   */
  int getExcludePlayerIdsCount();
  /**
   * <code>repeated int64 excludePlayerIds = 9;</code>
   */
  long getExcludePlayerIds(int index);

  public pb4server.MulticastEnvelopeMsg.CsMsgCase getCsMsgCase();
}
