// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal2public.proto

package pb4server;

/**
 * Protobuf type {@code pb4server.OpenAllianceWaijiaoAskRt}
 */
public  final class OpenAllianceWaijiaoAskRt extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb4server.OpenAllianceWaijiaoAskRt)
    OpenAllianceWaijiaoAskRtOrBuilder {
  // Use OpenAllianceWaijiaoAskRt.newBuilder() to construct.
  private OpenAllianceWaijiaoAskRt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OpenAllianceWaijiaoAskRt() {
    rt_ = 0;
    allianceWaijiaoInfos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private OpenAllianceWaijiaoAskRt(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            rt_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              allianceWaijiaoInfos_ = new java.util.ArrayList<pb4server.AllianceWaijiaoInfoVo>();
              mutable_bitField0_ |= 0x00000002;
            }
            allianceWaijiaoInfos_.add(
                input.readMessage(pb4server.AllianceWaijiaoInfoVo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        allianceWaijiaoInfos_ = java.util.Collections.unmodifiableList(allianceWaijiaoInfos_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pb4server.InternalPkt.internal_static_pb4server_OpenAllianceWaijiaoAskRt_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pb4server.InternalPkt.internal_static_pb4server_OpenAllianceWaijiaoAskRt_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pb4server.OpenAllianceWaijiaoAskRt.class, pb4server.OpenAllianceWaijiaoAskRt.Builder.class);
  }

  private int bitField0_;
  public static final int RT_FIELD_NUMBER = 1;
  private int rt_;
  /**
   * <code>int32 rt = 1;</code>
   */
  public int getRt() {
    return rt_;
  }

  public static final int ALLIANCEWAIJIAOINFOS_FIELD_NUMBER = 2;
  private java.util.List<pb4server.AllianceWaijiaoInfoVo> allianceWaijiaoInfos_;
  /**
   * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
   */
  public java.util.List<pb4server.AllianceWaijiaoInfoVo> getAllianceWaijiaoInfosList() {
    return allianceWaijiaoInfos_;
  }
  /**
   * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
   */
  public java.util.List<? extends pb4server.AllianceWaijiaoInfoVoOrBuilder> 
      getAllianceWaijiaoInfosOrBuilderList() {
    return allianceWaijiaoInfos_;
  }
  /**
   * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
   */
  public int getAllianceWaijiaoInfosCount() {
    return allianceWaijiaoInfos_.size();
  }
  /**
   * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
   */
  public pb4server.AllianceWaijiaoInfoVo getAllianceWaijiaoInfos(int index) {
    return allianceWaijiaoInfos_.get(index);
  }
  /**
   * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
   */
  public pb4server.AllianceWaijiaoInfoVoOrBuilder getAllianceWaijiaoInfosOrBuilder(
      int index) {
    return allianceWaijiaoInfos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rt_ != 0) {
      output.writeInt32(1, rt_);
    }
    for (int i = 0; i < allianceWaijiaoInfos_.size(); i++) {
      output.writeMessage(2, allianceWaijiaoInfos_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rt_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rt_);
    }
    for (int i = 0; i < allianceWaijiaoInfos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, allianceWaijiaoInfos_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pb4server.OpenAllianceWaijiaoAskRt)) {
      return super.equals(obj);
    }
    pb4server.OpenAllianceWaijiaoAskRt other = (pb4server.OpenAllianceWaijiaoAskRt) obj;

    boolean result = true;
    result = result && (getRt()
        == other.getRt());
    result = result && getAllianceWaijiaoInfosList()
        .equals(other.getAllianceWaijiaoInfosList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RT_FIELD_NUMBER;
    hash = (53 * hash) + getRt();
    if (getAllianceWaijiaoInfosCount() > 0) {
      hash = (37 * hash) + ALLIANCEWAIJIAOINFOS_FIELD_NUMBER;
      hash = (53 * hash) + getAllianceWaijiaoInfosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pb4server.OpenAllianceWaijiaoAskRt parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4server.OpenAllianceWaijiaoAskRt parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4server.OpenAllianceWaijiaoAskRt parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4server.OpenAllianceWaijiaoAskRt parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4server.OpenAllianceWaijiaoAskRt parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb4server.OpenAllianceWaijiaoAskRt parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb4server.OpenAllianceWaijiaoAskRt parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb4server.OpenAllianceWaijiaoAskRt parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb4server.OpenAllianceWaijiaoAskRt parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pb4server.OpenAllianceWaijiaoAskRt parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb4server.OpenAllianceWaijiaoAskRt parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb4server.OpenAllianceWaijiaoAskRt parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pb4server.OpenAllianceWaijiaoAskRt prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb4server.OpenAllianceWaijiaoAskRt}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb4server.OpenAllianceWaijiaoAskRt)
      pb4server.OpenAllianceWaijiaoAskRtOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb4server.InternalPkt.internal_static_pb4server_OpenAllianceWaijiaoAskRt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb4server.InternalPkt.internal_static_pb4server_OpenAllianceWaijiaoAskRt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb4server.OpenAllianceWaijiaoAskRt.class, pb4server.OpenAllianceWaijiaoAskRt.Builder.class);
    }

    // Construct using pb4server.OpenAllianceWaijiaoAskRt.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAllianceWaijiaoInfosFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      rt_ = 0;

      if (allianceWaijiaoInfosBuilder_ == null) {
        allianceWaijiaoInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        allianceWaijiaoInfosBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pb4server.InternalPkt.internal_static_pb4server_OpenAllianceWaijiaoAskRt_descriptor;
    }

    public pb4server.OpenAllianceWaijiaoAskRt getDefaultInstanceForType() {
      return pb4server.OpenAllianceWaijiaoAskRt.getDefaultInstance();
    }

    public pb4server.OpenAllianceWaijiaoAskRt build() {
      pb4server.OpenAllianceWaijiaoAskRt result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public pb4server.OpenAllianceWaijiaoAskRt buildPartial() {
      pb4server.OpenAllianceWaijiaoAskRt result = new pb4server.OpenAllianceWaijiaoAskRt(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.rt_ = rt_;
      if (allianceWaijiaoInfosBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          allianceWaijiaoInfos_ = java.util.Collections.unmodifiableList(allianceWaijiaoInfos_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.allianceWaijiaoInfos_ = allianceWaijiaoInfos_;
      } else {
        result.allianceWaijiaoInfos_ = allianceWaijiaoInfosBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pb4server.OpenAllianceWaijiaoAskRt) {
        return mergeFrom((pb4server.OpenAllianceWaijiaoAskRt)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pb4server.OpenAllianceWaijiaoAskRt other) {
      if (other == pb4server.OpenAllianceWaijiaoAskRt.getDefaultInstance()) return this;
      if (other.getRt() != 0) {
        setRt(other.getRt());
      }
      if (allianceWaijiaoInfosBuilder_ == null) {
        if (!other.allianceWaijiaoInfos_.isEmpty()) {
          if (allianceWaijiaoInfos_.isEmpty()) {
            allianceWaijiaoInfos_ = other.allianceWaijiaoInfos_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAllianceWaijiaoInfosIsMutable();
            allianceWaijiaoInfos_.addAll(other.allianceWaijiaoInfos_);
          }
          onChanged();
        }
      } else {
        if (!other.allianceWaijiaoInfos_.isEmpty()) {
          if (allianceWaijiaoInfosBuilder_.isEmpty()) {
            allianceWaijiaoInfosBuilder_.dispose();
            allianceWaijiaoInfosBuilder_ = null;
            allianceWaijiaoInfos_ = other.allianceWaijiaoInfos_;
            bitField0_ = (bitField0_ & ~0x00000002);
            allianceWaijiaoInfosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAllianceWaijiaoInfosFieldBuilder() : null;
          } else {
            allianceWaijiaoInfosBuilder_.addAllMessages(other.allianceWaijiaoInfos_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pb4server.OpenAllianceWaijiaoAskRt parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pb4server.OpenAllianceWaijiaoAskRt) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int rt_ ;
    /**
     * <code>int32 rt = 1;</code>
     */
    public int getRt() {
      return rt_;
    }
    /**
     * <code>int32 rt = 1;</code>
     */
    public Builder setRt(int value) {
      
      rt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rt = 1;</code>
     */
    public Builder clearRt() {
      
      rt_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<pb4server.AllianceWaijiaoInfoVo> allianceWaijiaoInfos_ =
      java.util.Collections.emptyList();
    private void ensureAllianceWaijiaoInfosIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        allianceWaijiaoInfos_ = new java.util.ArrayList<pb4server.AllianceWaijiaoInfoVo>(allianceWaijiaoInfos_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        pb4server.AllianceWaijiaoInfoVo, pb4server.AllianceWaijiaoInfoVo.Builder, pb4server.AllianceWaijiaoInfoVoOrBuilder> allianceWaijiaoInfosBuilder_;

    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public java.util.List<pb4server.AllianceWaijiaoInfoVo> getAllianceWaijiaoInfosList() {
      if (allianceWaijiaoInfosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(allianceWaijiaoInfos_);
      } else {
        return allianceWaijiaoInfosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public int getAllianceWaijiaoInfosCount() {
      if (allianceWaijiaoInfosBuilder_ == null) {
        return allianceWaijiaoInfos_.size();
      } else {
        return allianceWaijiaoInfosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public pb4server.AllianceWaijiaoInfoVo getAllianceWaijiaoInfos(int index) {
      if (allianceWaijiaoInfosBuilder_ == null) {
        return allianceWaijiaoInfos_.get(index);
      } else {
        return allianceWaijiaoInfosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public Builder setAllianceWaijiaoInfos(
        int index, pb4server.AllianceWaijiaoInfoVo value) {
      if (allianceWaijiaoInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllianceWaijiaoInfosIsMutable();
        allianceWaijiaoInfos_.set(index, value);
        onChanged();
      } else {
        allianceWaijiaoInfosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public Builder setAllianceWaijiaoInfos(
        int index, pb4server.AllianceWaijiaoInfoVo.Builder builderForValue) {
      if (allianceWaijiaoInfosBuilder_ == null) {
        ensureAllianceWaijiaoInfosIsMutable();
        allianceWaijiaoInfos_.set(index, builderForValue.build());
        onChanged();
      } else {
        allianceWaijiaoInfosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public Builder addAllianceWaijiaoInfos(pb4server.AllianceWaijiaoInfoVo value) {
      if (allianceWaijiaoInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllianceWaijiaoInfosIsMutable();
        allianceWaijiaoInfos_.add(value);
        onChanged();
      } else {
        allianceWaijiaoInfosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public Builder addAllianceWaijiaoInfos(
        int index, pb4server.AllianceWaijiaoInfoVo value) {
      if (allianceWaijiaoInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllianceWaijiaoInfosIsMutable();
        allianceWaijiaoInfos_.add(index, value);
        onChanged();
      } else {
        allianceWaijiaoInfosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public Builder addAllianceWaijiaoInfos(
        pb4server.AllianceWaijiaoInfoVo.Builder builderForValue) {
      if (allianceWaijiaoInfosBuilder_ == null) {
        ensureAllianceWaijiaoInfosIsMutable();
        allianceWaijiaoInfos_.add(builderForValue.build());
        onChanged();
      } else {
        allianceWaijiaoInfosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public Builder addAllianceWaijiaoInfos(
        int index, pb4server.AllianceWaijiaoInfoVo.Builder builderForValue) {
      if (allianceWaijiaoInfosBuilder_ == null) {
        ensureAllianceWaijiaoInfosIsMutable();
        allianceWaijiaoInfos_.add(index, builderForValue.build());
        onChanged();
      } else {
        allianceWaijiaoInfosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public Builder addAllAllianceWaijiaoInfos(
        java.lang.Iterable<? extends pb4server.AllianceWaijiaoInfoVo> values) {
      if (allianceWaijiaoInfosBuilder_ == null) {
        ensureAllianceWaijiaoInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, allianceWaijiaoInfos_);
        onChanged();
      } else {
        allianceWaijiaoInfosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public Builder clearAllianceWaijiaoInfos() {
      if (allianceWaijiaoInfosBuilder_ == null) {
        allianceWaijiaoInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        allianceWaijiaoInfosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public Builder removeAllianceWaijiaoInfos(int index) {
      if (allianceWaijiaoInfosBuilder_ == null) {
        ensureAllianceWaijiaoInfosIsMutable();
        allianceWaijiaoInfos_.remove(index);
        onChanged();
      } else {
        allianceWaijiaoInfosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public pb4server.AllianceWaijiaoInfoVo.Builder getAllianceWaijiaoInfosBuilder(
        int index) {
      return getAllianceWaijiaoInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public pb4server.AllianceWaijiaoInfoVoOrBuilder getAllianceWaijiaoInfosOrBuilder(
        int index) {
      if (allianceWaijiaoInfosBuilder_ == null) {
        return allianceWaijiaoInfos_.get(index);  } else {
        return allianceWaijiaoInfosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public java.util.List<? extends pb4server.AllianceWaijiaoInfoVoOrBuilder> 
         getAllianceWaijiaoInfosOrBuilderList() {
      if (allianceWaijiaoInfosBuilder_ != null) {
        return allianceWaijiaoInfosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(allianceWaijiaoInfos_);
      }
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public pb4server.AllianceWaijiaoInfoVo.Builder addAllianceWaijiaoInfosBuilder() {
      return getAllianceWaijiaoInfosFieldBuilder().addBuilder(
          pb4server.AllianceWaijiaoInfoVo.getDefaultInstance());
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public pb4server.AllianceWaijiaoInfoVo.Builder addAllianceWaijiaoInfosBuilder(
        int index) {
      return getAllianceWaijiaoInfosFieldBuilder().addBuilder(
          index, pb4server.AllianceWaijiaoInfoVo.getDefaultInstance());
    }
    /**
     * <code>repeated .pb4server.AllianceWaijiaoInfoVo allianceWaijiaoInfos = 2;</code>
     */
    public java.util.List<pb4server.AllianceWaijiaoInfoVo.Builder> 
         getAllianceWaijiaoInfosBuilderList() {
      return getAllianceWaijiaoInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        pb4server.AllianceWaijiaoInfoVo, pb4server.AllianceWaijiaoInfoVo.Builder, pb4server.AllianceWaijiaoInfoVoOrBuilder> 
        getAllianceWaijiaoInfosFieldBuilder() {
      if (allianceWaijiaoInfosBuilder_ == null) {
        allianceWaijiaoInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            pb4server.AllianceWaijiaoInfoVo, pb4server.AllianceWaijiaoInfoVo.Builder, pb4server.AllianceWaijiaoInfoVoOrBuilder>(
                allianceWaijiaoInfos_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        allianceWaijiaoInfos_ = null;
      }
      return allianceWaijiaoInfosBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:pb4server.OpenAllianceWaijiaoAskRt)
  }

  // @@protoc_insertion_point(class_scope:pb4server.OpenAllianceWaijiaoAskRt)
  private static final pb4server.OpenAllianceWaijiaoAskRt DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pb4server.OpenAllianceWaijiaoAskRt();
  }

  public static pb4server.OpenAllianceWaijiaoAskRt getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OpenAllianceWaijiaoAskRt>
      PARSER = new com.google.protobuf.AbstractParser<OpenAllianceWaijiaoAskRt>() {
    public OpenAllianceWaijiaoAskRt parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new OpenAllianceWaijiaoAskRt(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OpenAllianceWaijiaoAskRt> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OpenAllianceWaijiaoAskRt> getParserForType() {
    return PARSER;
  }

  public pb4server.OpenAllianceWaijiaoAskRt getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

