// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal2public.proto

package pb4server;

public interface QueryAllianceBossAskRtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb4server.QueryAllianceBossAskRt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rt = 1;</code>
   */
  int getRt();

  /**
   * <pre>
   * 召唤状态
   * </pre>
   *
   * <code>repeated .pb4server.AllianceBossVo allianceBossVos = 2;</code>
   */
  java.util.List<pb4server.AllianceBossVo> 
      getAllianceBossVosList();
  /**
   * <pre>
   * 召唤状态
   * </pre>
   *
   * <code>repeated .pb4server.AllianceBossVo allianceBossVos = 2;</code>
   */
  pb4server.AllianceBossVo getAllianceBossVos(int index);
  /**
   * <pre>
   * 召唤状态
   * </pre>
   *
   * <code>repeated .pb4server.AllianceBossVo allianceBossVos = 2;</code>
   */
  int getAllianceBossVosCount();
  /**
   * <pre>
   * 召唤状态
   * </pre>
   *
   * <code>repeated .pb4server.AllianceBossVo allianceBossVos = 2;</code>
   */
  java.util.List<? extends pb4server.AllianceBossVoOrBuilder> 
      getAllianceBossVosOrBuilderList();
  /**
   * <pre>
   * 召唤状态
   * </pre>
   *
   * <code>repeated .pb4server.AllianceBossVo allianceBossVos = 2;</code>
   */
  pb4server.AllianceBossVoOrBuilder getAllianceBossVosOrBuilder(
      int index);
}
