// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal2public.proto

package pb4server;

public interface QueryInAllianceRankReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb4server.QueryInAllianceRankReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 排行类型
   * </pre>
   *
   * <code>int32 rankType = 1;</code>
   */
  int getRankType();
}
