// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal2public.proto

package pb4server;

public interface SelectNowRankReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb4server.SelectNowRankReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 activityId = 1;</code>
   */
  int getActivityId();
}
