// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal2public.proto

package pb4server;

public interface SetAllianceMarkAskRtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb4server.SetAllianceMarkAskRt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rt = 1;</code>
   */
  int getRt();

  /**
   * <pre>
   *下次可再标记的结束时间戳
   * </pre>
   *
   * <code>int64 endTime = 2;</code>
   */
  long getEndTime();
}
