package com.point18.slg2d.mgr.rt4m

var allRightsMap = mutableMapOf<Int, String>()

fun newRtRight(code: Int, rightDesc: String): Int {
    allRightsMap[code] = rightDesc
    return code
}

// 把所有权限的map转为切片
fun getGameAllRightsMap(): MutableMap<Int, String> {
    return allRightsMap
}

val USER_LIST = newRtRight(1, "用户列表")
val USER_ADD = newRtRight(2, "添加用户")
val USER_MODIFY = newRtRight(3, "修改用户")
val USER_DEL = newRtRight(4, "删除用户")
val USER_QUERY = newRtRight(5, "查看用户")
val GROUP_CREATE = newRtRight(6, "创建用户群组")
val GROUP_MODIFY = newRtRight(7, "修改用户群组")
val GROUP_MODIFY_RIGHTS = newRtRight(8, "修改群组权限")
val GROUP_DEL = newRtRight(9, "删除群组")
val GROUP_ALL_QUERY = newRtRight(10, "查询群组")
val GROUP_QUERY = newRtRight(11, "查询单个群组")
val CHAT_LOG_QUERY = newRtRight(12, "查询聊天记录")
val DAILY_REPORT_QUERY = newRtRight(13, "查询日报")
val WEEKLY_REPORT_QUERY = newRtRight(14, "查询周报")
val GAG_QUERY = newRtRight(15, "查询禁言")
val GAG_ADD = newRtRight(16, "添加禁言")
val GAG_DEL = newRtRight(17, "删除禁言")
val GAME_AREA_QUERY = newRtRight(18, "查询游戏区")
val GAME_AREA_ADD = newRtRight(19, "添加游戏区")
val GAME_AREA_DEL = newRtRight(20, "删除游戏区")
val GAME_AREA_UPDATE = newRtRight(21, "更新游戏区")
val GAME_PROCESS_QUERY = newRtRight(22, "查询物理机")
val GAME_PROCESS_ADD = newRtRight(23, "添加物理机")
val GAME_PROCESS_DEL = newRtRight(24, "删除物理机")
val GAME_PROCESS_UPDATE = newRtRight(25, "更新物理机")
val IP_CLOSE_QUERY = newRtRight(26, "查询封号")
val IP_CLOSE_ADD = newRtRight(27, "添加封号")
val IP_CLOSE_DEL = newRtRight(28, "删除封号")
val MAIL_QUERY = newRtRight(29, "查询邮件")
val MAIL_SEND = newRtRight(30, "发送邮件")
val NOTICE_QUERY = newRtRight(31, "查询公告")
val NOTICE_DS_ADD = newRtRight(32, "添加定时公告")
val NOTICE_JS_ADD = newRtRight(33, "添加即时公告")
val NOTICE_DEL = newRtRight(34, "删除定时公告")
val PLATFORM_QUERY = newRtRight(35, "查询平台")
val PLATFORM_ADD = newRtRight(36, "添加平台")
val PLATFORM_DEL = newRtRight(37, "删除平台")
val PLATFORM_UPDATE = newRtRight(38, "修改平台")
val REMAIN_QUERY = newRtRight(39, "查询账号留存和流失")
val CARD_GIFT = newRtRight(40, "发放卡牌")
val PLAYER_QUERY = newRtRight(41, "查询玩家具体信息")
val RANK_QUERY = newRtRight(42, "查询排行榜")
val PLAYER_LOG_QUERY = newRtRight(43, "查询玩家日志")
val ROSTER_QUERY = newRtRight(44, "查询黑白名单")
val ROSTER_ADD = newRtRight(45, "添加黑白名单")
val ROSTER_DEL = newRtRight(46, "删除黑白名单")
val SHIELD_WORD_QUERY = newRtRight(47, "查询屏蔽词")
val SHIELD_WORD_ADD = newRtRight(48, "添加屏蔽词")
val SHIELD_WORD_DEL = newRtRight(49, "删除屏蔽词")
val ONLINE_NUM_QUERY = newRtRight(50, "查询在线人数")
val RECHARGE_QUERY = newRtRight(51, "充值查询")
val GM_LOG_QUERY = newRtRight(52, "后台操作日志查询")
val LOGIN = newRtRight(53, "登录")
val AREA_CLOSE = newRtRight(54, "关闭游戏区")
val AREA_DEL = newRtRight(55, "删除游戏区")
val AREA_CLEAN = newRtRight(56, "删档")
val AREA_ADD = newRtRight(57, "部署游戏区")
val MAIL_DEL = newRtRight(58, "删除邮件")
val LOG_CONFIG_ADD = newRtRight(60, "添加日志服")
val LOG_CONFIG_DEL = newRtRight(61, "日志服删除")
val LOG_CONFIG_UPDATE = newRtRight(62, "日志服更新")
val LOG_CONFIG_QUERY = newRtRight(63, "日志服查询")
val NEW_GUIDE_REMAIN = newRtRight(64, "新手引导留存")
val ACCOUNT_REMAIN = newRtRight(65, "账号留存")
val AREA_SWITCH_MAINTANCE = newRtRight(66, "切换维护状态")
val LOGIN_SERVER_ADD = newRtRight(67, "添加登陆服")
val LOGIN_SERVER_DEL = newRtRight(68, "删除登陆服")
val LOGIN_SERVER_UPDATE = newRtRight(69, "更新登陆服")
val LOGIN_SERVER_QUERY = newRtRight(70, "查询登陆服")
val CHAT_SERVER_ADD = newRtRight(71, "添加聊天服")
val CHAT_SERVER_QUERY = newRtRight(72, "查询聊天服")
val CHAT_SERVER_UPDATE = newRtRight(73, "修改聊天服")
val CHAT_SERVER_DEL = newRtRight(74, "删除聊天服")
val PUBLIC_SERVER_ADD = newRtRight(75, "添加PUBLIC服")
val PUBLIC_SERVER_DEL = newRtRight(76, "删除PUBLIC服")
val PUBLIC_SERVER_UPDATE = newRtRight(77, "修改PUBLIC服")
val MAP_SERVER_ADD = newRtRight(78, "添加地图服")
val MAP_SERVER_DEL = newRtRight(79, "删除地图服")
val MAP_SERVER_UPDATE = newRtRight(80, "修改地图服")
val ADD_COMM_CFG = newRtRight(81, "添加集群配置")
val DEL_COMM_CFG = newRtRight(82, "删除集群配置")
val CHG_COMM_CFG = newRtRight(83, "修改集群配置")
val QUERY_COMM_CFG = newRtRight(84, "查询集群配置")
