package com.point18.slg2d.common.constg

const val OPEN_SETTING_TEST = true

// 通知设置
// DEVELOP_SETTING 内城发展
const val BUILDING_UP_SETTING = 1001 // 建造完成
const val RESEARCH_UP_SETTING = 1002 // 科技提升
const val SOLDIER_MAKE_SETTING = 1003 // 造兵 造陷阱

// PERSONAL_MILITARY_SETTING 个人军事
const val BE_ATTACKED = 2001
const val BE_SCOUTED = 2002
const val BE_MASSED_1H = 2003
const val BE_MASSED_8H = 2004

// ALLIANCE_MILITARY_SETTING 联盟军事
const val ALLIANCE_MASS_1H = 3001
const val ALLIANCE_BE_MASSED_1H = 3002
const val ALLIANCE_MASS_8H = 3003
const val ALLIANCE_BE_MASSED_8H = 3004
const val ALLIANCE_MASS_RELIC = 3005

// WONDER_MILITARY_SETTING 奇观军事
const val WONDER_BE_ATTACKED = 4001
const val WONDER_BE_SCOUTED = 4002
const val WONDER_BE_MASSED = 4003

// ACTIVITY_SETTING 活动

// WALK_GROUP_SETTING 行军
const val FARM_GROUP_BACK = 6001
const val TRANSPORT_GROUP_BACK = 6002
const val MASS_GROUP_BACK = 6003
const val REINFORCE_GROUP_BACK = 6004
const val STATION_GROUP_BACK = 6005
const val WONDER_REINFORCE_GROUP_BACK = 6006

// PRISON_SETTING 监狱
const val PRISON_EXECUTION_SETTING = 7001
const val PRISON_EAT_POISON_SETTING = 7002
const val PRISON_RELEASE_SETTING = 7003

// GET_AWARD_SETTING 奖励
const val ALLIANCE_AWARD_SETTING = 8001

// RESOURCE_SETTING 资源 行动力 体力


// BUFF_EFFECT_SETTING buff效果


// SOCIAL_SETTING 社交
const val NEW_MAIL_SETTING = 11001

// JJC_SETTING 竞技场
const val JJC_RANK_SETTING = 12001

// CAVE_SETTING 藏兵


// MERCHANT_SHIP_SETTING 商船
